---
title: "expression_analyses"
author: "Leroy Bondhus"
date: "2023-10-24"
output: html_document
editor_options: 
  chunk_output_type: console
---





<!-- ```{r, add summary level expr data to ontology} -->
<!-- onto <- ontos$uberon$ont -->
<!-- mat <- dataset_list$ENCODE_HH$agg_med_norm__mat -->
<!-- coldata <- dataset_list$ENCODE_HH$agg_med_norm__coldata -->
<!-- num_terms <- length(onto$id) -->
<!-- num_features <- nrow(mat) -->
<!-- # onto$ehh_summary_stats <- list( -->
<!-- #   mean_internal = vector("list", num_terms), -->
<!-- #   sd_internal = vector("list", num_terms), -->
<!-- #   tau_internal = vector("list", num_terms), -->
<!-- #   mean_external = vector("list", num_terms), -->
<!-- #   sd_external = vector("list", num_terms), -->
<!-- #   tau_external = vector("list", num_terms) -->
<!-- # ) -->
<!-- onto$ehh_summary_stats <- vector("list", num_terms) -->
<!-- temp_stat_df_model <- data.frame( -->
<!--   mean_internal = numeric(length=num_features), -->
<!--   sd_internal = numeric(length=num_features), -->
<!--   tau_internal = numeric(length=num_features), -->
<!--   mean_external = numeric(length=num_features), -->
<!--   sd_external = numeric(length=num_features), -->
<!--   tau_external = numeric(length=num_features) -->
<!-- ) -->
<!-- rownames(temp_stat_df_model) <- rownames(mat) -->



<!-- temp_num_els <- sapply(onto$ehh,length) -->
<!-- # temp_els <- is.element(onto$id, onto$descendants[[grep("^mesoderm-derived",onto$name)]]) -->
<!-- # temp_els <- grepl("^heart$",onto$name) -->
<!-- # temp_els <- temp_els | grepl("^mesoderm-derived",onto$name) -->
<!-- # temp_els <- temp_els | grepl("^anatomical entity$",onto$name) -->
<!-- # temp_els <- which(temp_els & temp_num_els > 1) -->

<!-- eg_onto_terms <- c("anatomical entity","mesoderm-derived structure","heart","muscle tissue", -->
<!--                     "cardiac muscle tissue", "skeletal muscle tissue","smooth muscle tissue") -->
<!-- temp_els <- match(eg_onto_terms, onto$name) -->

<!-- #temp_els <- which(is.element(onto$id, onto$descendants[[grep("^mesoderm-derived",onto$name)]]) & -->
<!-- #                  temp_num_els > 1)   #which(temp_num_els > 1) -->
<!-- #temp_els <- grep("^mesoderm-derived|^ectoderm-derived|^endoderm-derived", onto$name) -->
<!-- for(i in 1:length(temp_els)){ -->
<!--   print(i) -->

<!--   ehh <- onto$ehh[[temp_els[i]]] -->
<!--   onto$ehh_summary_stats[[temp_els[i]]] <- temp_stat_df_model -->

<!--   for(set_and_complement in c(1,-1)){ -->
<!--     if(set_and_complement==1){print("set")} else {print("complement")} -->
<!--     temp_mat <- mat[,ehh*set_and_complement,drop=F] -->
<!--     temp_coldata <- coldata[ehh*set_and_complement,,drop=F] -->
<!--     if(ncol(temp_mat)>0 & (length(ehh) > 5 | set_and_complement==1) ){ -->
<!--       colnames(temp_mat) <- make.unique(paste0(temp_coldata$biosample_ontology.term_name, -->
<!--                                                ":",temp_coldata$age_group)) -->
<!--       dot_sim <- similarity_func(temp_mat) -->
<!--       rownames(dot_sim) <- colnames(dot_sim) <- colnames(temp_mat) -->
<!--       sim_tree <- cluster_func(dot_sim) -->
<!--       weights <- get_weights(sim_tree, colnames(temp_mat)) -->
<!--       weighted_means <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.mean(x, weights=weights)}) -->
<!--       weighted_sds <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.var(x, weights=weights)}) -->
<!--       temp_tau <- calc_weighted_tau(temp_mat,weights) -->
<!--     } else { -->
<!--       temp_tau <- NA -->
<!--       weighted_means <- NA -->
<!--       weighted_sds <- NA -->
<!--     } -->
<!--     if(set_and_complement==1){ -->
<!--       # onto$ehh_summary_stats$tau_internal[[temp_els[i]]] <- temp_tau -->
<!--       # onto$ehh_summary_stats$mean_internal[[temp_els[i]]] <- weighted_means -->
<!--       # onto$ehh_summary_stats$sd_internal[[temp_els[i]]] <- weighted_sds -->
<!--       onto$ehh_summary_stats[[temp_els[i]]]$tau_internal <- temp_tau -->
<!--       onto$ehh_summary_stats[[temp_els[i]]]$mean_internal <- weighted_means -->
<!--       onto$ehh_summary_stats[[temp_els[i]]]$sd_internal <- weighted_sds -->
<!--     } else { -->
<!--       onto$ehh_summary_stats[[temp_els[i]]]$tau_external <- temp_tau -->
<!--       onto$ehh_summary_stats[[temp_els[i]]]$mean_external <- weighted_means -->
<!--       onto$ehh_summary_stats[[temp_els[i]]]$sd_external <- weighted_sds -->
<!--     } -->

<!--   } -->
<!-- } -->


<!-- save.image("post_summ_stat_meso.RData") -->
<!-- ``` -->

```{r, plot broad level expression}

temp_mat <- dataset_list$ENCODE_HH$agg_med_norm__mat
temp_coldata <- dataset_list$ENCODE_HH$agg_med_norm__coldata

colnames(temp_mat) <- make.unique(paste(temp_coldata$assay_term_name,
                                         temp_coldata$biosample_ontology.term_name,
                                         temp_coldata$age_group, sep=":"))


dot_sim <- similarity_func(temp_mat)
rownames(dot_sim) <- colnames(dot_sim) <- colnames(temp_mat)
sim_tree <- cluster_func(dot_sim)
weights <- get_weights(sim_tree, colnames(temp_mat))
weighted_means <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.mean(x, weights=weights)})
weighted_sds <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.var(x, weights=weights)})
temp_tau <- calc_weighted_tau(temp_mat,weights)

ggl2 <- list()
for(subset_name in names(gene_sets$human_chromatin_modifiers$gene_subsets)){ 
  which <- which(is.element(rownames(temp_mat),gene_sets$human_chromatin_modifiers$gene_subsets[[subset_name]] ))
  sub_temp_mat <- temp_mat[which,]
  sub_temp_mat <- melt(sub_temp_mat)
  colnames(sub_temp_mat) <- c("id","biosample","expr")
  sub_temp_mat$name <- gene_sets$genes_all$external_gene_name[match(sub_temp_mat$id,gene_sets$genes_all$ensembl_gene_id)]
  sub_temp_mat$name[which(sub_temp_mat$name=="")] <- sub_temp_mat$id[which(sub_temp_mat$name=="")]
  temp <- str_split_fixed(sub_temp_mat$biosample,":", 3)
  colnames(temp) <- c("assay","ontology.term_name","age_group")
  sub_temp_mat <- cbind(sub_temp_mat, temp)
  
  
  df <- data.frame(id = names(weighted_means)[which],
                   wmean = weighted_means[which],
                   wvar = weighted_sds[which],
                   name = gene_sets$genes_all$external_gene_name[match(rownames(temp_mat)[which],gene_sets$genes_all$ensembl_gene_id)])
  df$name[which(df$name=="")] <- df$id[which(df$name=="")]
  df <- df[order(df$wmean, decreasing=T),]
  df$id <- factor(df$id, levels = df$id)
  df$name <- factor(df$name, levels = df$name)
  df$wmeanv_l <- df$wmean - df$wvar
  df$wmeanv_u <- df$wmean + df$wvar
  
  sub_temp_mat$name <- factor(sub_temp_mat$name,levels=levels(df$name))
  ggl2[[str_replace_all(subset_name," ","_")]] <- ggplot(df, aes(x=wmean,y=name))+
    geom_point(color="grey20")+
    geom_point(data = sub_temp_mat, aes(x=expr, y = name),size=0.1,alpha=0.4
               ,color="salmon")+
    geom_errorbar(alpha=0.8,color="grey20",aes(xmin=wmeanv_l,xmax=wmeanv_u))+
    scale_y_discrete(limits=levels(df$name))+
    scale_x_continuous(limits = c(0,3.5))+
    theme_bw()+
    theme(axis.text.y = element_text(size=2))
  ggsave(paste0(dirs$figures, str_replace_all(subset_name," ","_"), "_dist.png"),dev="png",units = "in",width=8,height=10)
  
  
  # ggplot(df, aes(x=wmean))+
  #   geom_histogram(aes(y=..density..), position="identity") +
  #   geom_density(aes(y=..density..))
  # ggsave(paste0(dirs$figures,"expression_dist.png"),dev="png",units = "in",width=8,height=4)
  #
  
  
  ggl <- list()
  ggl[["density"]] <- ggplot(df, aes(x=wmean))+
    geom_density(alpha=0.5)+
    barcode_theme+
    theme(axis.title.x = element_blank())
  
  ggl[["barcode"]] <- ggplot(df, aes(x=wmean,xend=wmean, y=0,yend=1))+
    geom_segment(alpha=0.5)+
    barcode_theme+
    theme(strip.text.y = element_text(angle = 0))
  
  ggl[["composite"]] <- plot_grid(ggl$density, ggl$barcode, align="v",axis="r",nrow = 2, rel_heights = c(1,1))
  ggl$composite
  
  filename <- paste0(dirs$figures, str_replace_all(subset_name," ","_"), "_expression_dist.png")
  save_plot(filename = filename, ggl$composite, base_width = 6, base_height=2)
}

ggl2$composite <- plot_grid(ggl2$non_histones, ggl2$structural_constituent_of_chromatin, align="v",axis="r",nrow = 2, rel_heights = c(3,1))
filename <- paste0(dirs$figures,  "histone_nonhistone_expression_dist.png")
save_plot(filename = filename, ggl2$composite, base_width = 6, base_height=8)
```

```{r, histone vs chrom modifiers}
gene_sets$human <- list()
gene_sets$human$cell_cycle <- gene_sets$genes_all_go$ensembl_gene_id[
  which(is.element(gene_sets$genes_all_go$go_id, 
                   c(ontos$go$ont$id[which(ontos$go$ont$name=="regulation of mitotic cell cycle")],
                     ontos$go$ont$descendants[[which(ontos$go$ont$name=="regulation of mitotic cell cycle")]]) ))
]
subset_names <- c("structural constituent of chromatin","non_histones","regulation of mitotic cell cycle")
full_df <- NULL
full_temp_mat  <- NULL
subsets <- list("structural constituent of chromatin" = gene_sets$human_chromatin_modifiers$gene_subsets$`structural constituent of chromatin`,
                "non_histones" = gene_sets$human_chromatin_modifiers$gene_subsets$non_histones,
                "regulation of mitotic cell cycle" = gene_sets$human$cell_cycle)


major_anatomic_groups <- c("genitourinary system",
                           "nervous system",
                           "cardiovascular system",
                           "musculoskeletal system",
                           "integumental system",
                           "immune system",
                           "digestive system",
                           "respiratory system",
                           "hematopoietic system",
                           "endocrine system",
                           "limb")
all(is.element(major_anatomic_groups, ontos$uberon$ont$name))


temp_coldata$mat_colnames <- paste(temp_coldata$assay_term_name,
                                   temp_coldata$biosample_ontology.term_name,
                                   temp_coldata$age_group,sep=":")
temp_coldata$major_anatomic_group <- ""
for(anatomic_group in major_anatomic_groups){
  which <- ontos$uberon$ont$ehh[[which(ontos$uberon$ont$name==anatomic_group)]]
  temp_coldata$major_anatomic_group[which] <- str_remove(paste(temp_coldata$major_anatomic_group[which],
                                                    str_remove(anatomic_group," system"),sep=","),"^,") 
}

for(subset_name in subset_names){
  which <- which(is.element(rownames(temp_mat),subsets[[subset_name]]))
  sub_temp_mat <- temp_mat[which,]
  sub_temp_mat <- melt(sub_temp_mat)
  colnames(sub_temp_mat) <- c("id","biosample","expr")
  sub_temp_mat$name <- gene_sets$genes_all$external_gene_name[match(sub_temp_mat$id,gene_sets$genes_all$ensembl_gene_id)]
  sub_temp_mat$name[which(sub_temp_mat$name=="")] <- sub_temp_mat$id[which(sub_temp_mat$name=="")]
  temp <- str_split_fixed(sub_temp_mat$biosample,":", 3)
  colnames(temp) <- c("assay","ontology.term_name","age_group")
  sub_temp_mat <- cbind(sub_temp_mat, temp)
  
  
  df <- data.frame(id = names(weighted_means)[which],
                   wmean = weighted_means[which],
                   wvar = weighted_sds[which],
                   name = gene_sets$genes_all$external_gene_name[match(rownames(temp_mat)[which],gene_sets$genes_all$ensembl_gene_id)])
  df$name[which(df$name=="")] <- df$id[which(df$name=="")]
  df <- df[order(df$wmean, decreasing=T),]
  df$id <- factor(df$id, levels = df$id)
  df$name <- factor(df$name, levels = df$name)
  df$wmeanv_l <- df$wmean - df$wvar
  df$wmeanv_u <- df$wmean + df$wvar
  
  
  
  full_df <- unique(rbind(full_df,df))
  full_temp_mat <- unique(rbind(full_temp_mat, sub_temp_mat))
}

full_temp_mat$major_anatomic_group <-  temp_coldata$major_anatomic_group[match(full_temp_mat$biosample, temp_coldata$mat_colnames)]
full_temp_mat$major_anatomic_group[which(str_length(full_temp_mat$major_anatomic_group)>15)]  <- "" 

ggplot(full_df, aes(x=wmean,y=name))+
  geom_point(color="grey20")+
  geom_point(data = full_temp_mat[which(full_temp_mat$major_anatomic_group!=""),],
             aes(x=expr, y = name, color=major_anatomic_group),size=0.1,alpha=0.4)+# ,color="salmon")+
  geom_errorbar(alpha=0.8,color="grey20",aes(xmin=wmeanv_l,xmax=wmeanv_u))+
  scale_y_discrete(limits=levels(full_df$name))+
  scale_x_continuous(limits = c(0,3.5))+
  theme_bw()+
  theme(axis.text.y = element_text(size=2))


filename <- paste0(dirs$figures,  "histone_nonhistone_cellcycle_expression_dist.png")
ggsave(filename = filename,dev="png",units = "in",width=8,height=14,dpi=350)


for(major_anatomic_group in unique(full_temp_mat$major_anatomic_group)){
  ggplot(full_df, aes(x=wmean,y=name))+
    geom_point(color="grey20")+
    geom_point(data = full_temp_mat[which(full_temp_mat$major_anatomic_group!=""),],
             aes(x=expr, y = name), color="grey20",size=0.1,alpha=0.4)+# ,color="salmon")+
    geom_point(data = full_temp_mat[which(full_temp_mat$major_anatomic_group==major_anatomic_group),],
               aes(x=expr, y = name), color="red",size=0.1,alpha=0.6)+# ,color="salmon")+
    geom_errorbar(alpha=0.6,color="grey10",aes(xmin=wmeanv_l,xmax=wmeanv_u))+
    scale_y_discrete(limits=levels(full_df$name))+
    scale_x_continuous(limits = c(0,3.5))+
    theme_bw()+
    theme(axis.text.y = element_text(size=2))

  filename <- paste0(dirs$figures,  "histone_nonhistone_cellcycle_expression_dist_",major_anatomic_group,".png")
  ggsave(filename = filename,dev="png",units = "in",width=8,height=12,dpi=300)
}


# 
# cor_mat <- matrix(nrow=length(unlist(subsets)),
#                   ncol=length(unlist(subsets)))
# rownames(cor_mat) <- colnames(cor_mat) <- unlist(subsets)
# which <- which(is.element(unlist(subsets),rownames(temp_mat)))
# cor_mat <- cor_mat[which,which]
# which <- sort(sample(1:nrow(cor_mat),300))
# cor_mat <- cor_mat[which,which]

# 

cor_mat <- matrix(nrow=length(c(subsets$`regulation of mitotic cell cycle`)),
                  ncol=length(c(subsets$`regulation of mitotic cell cycle`)))
rownames(cor_mat) <- colnames(cor_mat) <- c(subsets$`regulation of mitotic cell cycle`)
which <- which(is.element(c(subsets$`regulation of mitotic cell cycle`),rownames(temp_mat)))
cor_mat <- cor_mat[which,which]
which <- sort(sample(1:nrow(cor_mat),300))
cor_mat <- cor_mat[which,which]
for(i in 1:nrow(cor_mat)){
  if(i %% 20 ==0 ){print(i)}
  if(var(temp_mat[i,])<1e-10){next}
  for(j in 1:nrow(cor_mat)){
    if(var(temp_mat[j,])<1e-10){next}
    cor_mat[i,j] <-cor(temp_mat[rownames(cor_mat)[i],], temp_mat[rownames(cor_mat)[j],])
  }
}
Heatmap(cor_mat)


cor_mat <- matrix(nrow=length(c(subsets$`regulation of mitotic cell cycle`)),
                  ncol=length(c(subsets$`structural constituent of chromatin`)))
rownames(cor_mat) <- c(subsets$`regulation of mitotic cell cycle`)
which <- which(is.element(c(subsets$`regulation of mitotic cell cycle`),rownames(temp_mat)))
cor_mat <- cor_mat[which,]
colnames(cor_mat) <- c(subsets$`structural constituent of chromatin`)
which <- which(is.element(c(subsets$`structural constituent of chromatin`),rownames(temp_mat)))
cor_mat <- cor_mat[,which]
which <- sort(sample(1:nrow(cor_mat),300))
cor_mat <- cor_mat[which,]

for(i in 1:nrow(cor_mat)){
  if(i %% 20 ==0 ){print(i)}
  if(var(temp_mat[i,])<1e-10){next}
  for(j in 1:ncol(cor_mat)){
    if(var(temp_mat[j,])<1e-10){next}
    cor_mat[i,j] <-cor(temp_mat[rownames(cor_mat)[i],], temp_mat[colnames(cor_mat)[j],])
  }
}
Heatmap(cor_mat)


```


```{r, set up major systems}
### set building
### build major systems UBERON and HPO sets
# 
# major_systems<- c("nervous system",
#                   "cardiovascular system",
#                   "musculoskeletal system",
#                   "respiratory system",
#                   "digestive system",
#                   "renal system",
#                   "reproductive system",
#                   "immune system",
#                   "endocrine system",
#                   "hematopoietic system",
#                   "integumental system")
# 
# ### major system name, ontology name, ontology id, include/remove (T/F)
# major_systems <- matrix(nrow = 0, ncol=4)
# ### Uberon Canon
# major_systems <- rbind(major_systems,c("nervous system", "nervous system", "UBERON:0001016",T) )
# major_systems <- rbind(major_systems,c("nervous system", "nervous system", "UBERON:0001016",T))
# major_systems <- rbind(major_systems,c("cardiovascular system","cardiovascular system","UBERON:0004535",T))
# major_systems <- rbind(major_systems,c("musculoskeletal system","musculoskeletal system","UBERON:0002204",T))
# major_systems <- rbind(major_systems,c("respiratory system","respiratory system","UBERON:0001004",T))
# major_systems <- rbind(major_systems,c("digestive system","digestive system","UBERON:0001007",T))
# major_systems <- rbind(major_systems,c("renal system","renal system","UBERON:0001008",T))
# major_systems <- rbind(major_systems,c("reproductive system","reproductive system","UBERON:0000990",T))
# major_systems <- rbind(major_systems,c("immune system","immune system","UBERON:0002405",T))
# major_systems <- rbind(major_systems,c("endocrine system","endocrine system","UBERON:0000949",T))
# major_systems <- rbind(major_systems,c("hematopoietic system","hematopoietic system","UBERON:0002390",T))
# major_systems <- rbind(major_systems,c("integumental system","integumental system","UBERON:0002416",T))
# ## UBERON non-canon
# major_systems <- rbind(major_systems,c("musculoskeletal system","musculature of body","UBERON:0002204",T))
# "v")]],"musculoskeletal system"] 


```




```{r, make primary gene expression heatmap figure}
onto <- ontos$hpo$ont
which <- which(onto$name=="Phenotypic abnormality")
major_systems <- onto$name[is.element(onto$id,onto$children[[which]])]
to_remove <- c("Constitutional symptom",
               "Abnormality of the thoracic cavity",
               "Abnormality of prenatal development or birth",
               "Neoplasm",
               "Abnormal cellular phenotype",
               "Growth abnormality")
major_systems <- major_systems[-which(is.element(major_systems,to_remove ))]
temp_ids <- onto$id[match(major_systems,onto$name)]
temp_df <- onto_maps$HPO_UBERON$map[match(temp_ids, onto_maps$HPO_UBERON$map$HPO_ID),]
temp_df$HPO_name <- ontos$hpo$ont$name[match(temp_df$HPO_ID, ontos$hpo$ont$id)]
temp_df$UBERON_name <- ontos$uberon$ont$name[match(temp_df$UBERON_ID, ontos$uberon$ont$id)]
## map major systems defined in HPO to UBERON



#major_systems <- list(system_name=major_systems,
                      # descendent_ids=vector(mode="list",length=length(major_systems))  )

# for(i in 1:length(major_systems$descendent_ids)){
#   major_systems$descendent_ids[[i]] <- onto$descendants[[which(onto$name== major_systems$system_name[i] )]]
# }






#### top : ubiquitous ordered by decreasing mean expression
### bottom : Specific - top 10 by major system -- map UBERON to same set of major systems as HPO phenotype analyses
## OR for each specific gene - search onto list - pull df of mean and specificity of int and ext
## then calc sim of this for all spec genes (i.e. cluster on this) - and plot with these gene groups and columns ordered by
## these onto terms- allow duplicates ?
### complex : correlation with other gene classes? GO analysis to id unifying modules ? (since not related by tissue)



```




<!-- ```{r, muscle example r.e. ontologically organized analysis} -->
<!-- onto <- ontos$uberon$ont -->
<!-- mat <- dataset_list$ENCODE_HH$agg_med_norm__mat -->
<!-- coldata <- dataset_list$ENCODE_HH$agg_med_norm__coldata -->

<!-- #### ubiquitous, specific -->
<!-- #### all, mesoderm-derived, heart -->

<!-- temp_stat_df_model <- data.frame( -->
<!--   mean_internal = numeric(length=num_features), -->
<!--   sd_internal = numeric(length=num_features), -->
<!--   tau_internal = numeric(length=num_features), -->
<!--   mean_external = numeric(length=num_features), -->
<!--   sd_external = numeric(length=num_features), -->
<!--   tau_external = numeric(length=num_features) -->
<!-- ) -->
<!-- rownames(temp_stat_df_model) <- rownames(mat) -->

<!-- ## assumes p2 can contain p1 but not reverse -->
<!-- contrast_pairs <- list(list(name="muscle v all", -->
<!--                             p1="muscle tissue", -->
<!--                             p2="anatomical entity"), -->
<!--                        list(name="striated muscle v other muscle", -->
<!--                             p1="striated muscle tissue", -->
<!--                             p2="muscle tissue"), -->
<!--                        list(name="cardiac muscle v other muscle", -->
<!--                             p1="cardiac muscle tissue", -->
<!--                             p2="muscle tissue"), -->
<!--                        list(name="skeletal muscle v other muscle", -->
<!--                             p1="skeletal muscle tissue", -->
<!--                             p2="muscle tissue"), -->
<!--                        list(name="smooth muscle v other muscle", -->
<!--                             p1="smooth muscle tissue", -->
<!--                             p2="muscle tissue")) #, -->
<!--                        # list(name="striated muscle v all", -->
<!--                        #      p1="striated muscle tissue", -->
<!--                        #      p2="anatomical entity"), -->
<!--                        # list(name="cardiac muscle v all", -->
<!--                        #      p1="cardiac muscle tissue", -->
<!--                        #      p2="anatomical entity"), -->
<!--                        # list(name="skeletal muscle v all", -->
<!--                        #      p1="skeletal muscle tissue", -->
<!--                        #      p2="anatomical entity"), -->
<!--                        # list(name="smooth muscle v all", -->
<!--                        #      p1="smooth muscle tissue", -->
<!--                        #      p2="anatomical entity")) -->

<!-- for(i in 1:length(contrast_pairs)){ -->
<!--   temp_pair <- contrast_pairs[[i]] -->
<!--   print(temp_pair$name) -->

<!--   colset_list <- list( -->
<!--     ehh1 = onto$ehh[[which(onto$name==temp_pair$p1) ]], -->
<!--     ehh2 = setdiff(onto$ehh[[which(onto$name==temp_pair$p2)]] -->
<!--                    ,onto$ehh[[which(onto$name==temp_pair$p1)]]) -->
<!--   ) -->
<!--   temp_pair$summary_stats <- temp_stat_df_model -->
<!--   for(j in 1:length(colset_list)){ -->
<!--     ehh <- colset_list[[j]] -->
<!--     temp_mat <- mat[,ehh,drop=F] -->
<!--     temp_coldata <- coldata[ehh,,drop=F] -->
<!--     colnames(temp_mat) <- make.unique(paste0(temp_coldata$biosample_ontology.term_name, -->
<!--                                              ":",temp_coldata$age_group)) -->
<!--     dot_sim <- similarity_func(temp_mat) -->
<!--     rownames(dot_sim) <- colnames(dot_sim) <- colnames(temp_mat) -->
<!--     sim_tree <- cluster_func(dot_sim) -->
<!--     weights <- get_weights(sim_tree, colnames(temp_mat)) -->
<!--     if(names(colset_list)[j]=="ehh1"){ -->
<!--       temp_pair$summary_stats$mean_internal <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.mean(x, weights=weights)}) -->
<!--       temp_pair$summary_stats$sd_internal <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.var(x, weights=weights)}) -->
<!--       temp_pair$summary_stats$tau_internal <- calc_weighted_tau(temp_mat,weights) -->
<!--     }else{ -->
<!--       temp_pair$summary_stats$mean_external <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.mean(x, weights=weights)}) -->
<!--       temp_pair$summary_stats$sd_external <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.var(x, weights=weights)}) -->
<!--       temp_pair$summary_stats$tau_external <- calc_weighted_tau(temp_mat,weights) -->
<!--     } -->
<!--   } -->
<!--   contrast_pairs[[i]] <- temp_pair -->

<!-- } -->

<!-- save.image("post_contrast_muscle.RData") -->
<!-- ``` -->


```{r, get gene sets to plot}
gene_sets$to_plot <- list()
gene_sets$to_plot_full_ordered <- list()

for(i in 1:length(contrast_pairs)){
  temp_df <- contrast_pairs[[i]]$summary_stats
  temp_df$delta_mean <- temp_df$mean_internal - temp_df$mean_external
  temp_df$delta_tau <- temp_df$tau_external - temp_df$tau_internal
  which <- which(temp_df$mean_internal > 0.5 &
                   abs(temp_df$delta_mean) > 0.5 &
                   temp_df$sd_internal < (temp_df$mean_internal/2) &
                   temp_df$tau_internal < 0.4 )
  print(paste0(contrast_pairs[[i]]$name,":",length(which)))

  # gene_sets$genes_all$external_gene_name[match(rownames(temp_df[which,]),gene_sets$genes_all$ensembl_gene_id)]
  temp_df2 <- cbind(temp_df,data.frame(gene_id=rownames(temp_df)))
  temp_df2 <- merge(temp_df2, gene_sets$genes_all[,c(1,2)],by.x="gene_id",by.y="ensembl_gene_id")
  temp_df2 <- temp_df2[which,]

  temp_df2_pos <- temp_df2[which(temp_df2$delta_mean > 0),]
  temp_df2_neg <- temp_df2[which(temp_df2$delta_mean < 0),]

  if(nrow(temp_df2_pos) > 0){
  #  top_10_pos <- temp_df2_pos[order(temp_df2_pos$delta_mean, decreasing = T),c("gene_id","external_gene_name")]
    top_10_pos <- temp_df2_pos[order(temp_df2_pos$delta_mean, decreasing = T)[1:min(8,nrow(temp_df2_pos))],c("gene_id","external_gene_name")]
    full_ordered<- temp_df2_pos[order(temp_df2_pos$delta_mean, decreasing = T),]
  } else {  top_10_pos <- NA }
  if(nrow(temp_df2_neg >0)){
  #  top_10_neg <- temp_df2_neg[order(temp_df2_neg$delta_mean, decreasing = T),c("gene_id","external_gene_name")]
    top_10_neg <- temp_df2_neg[order(temp_df2_neg$delta_mean, decreasing = T)[1:min(8,nrow(temp_df2_neg))],c("gene_id","external_gene_name")]
  } else { top_10_neg <- NA }


  gene_sets$to_plot[[paste0(contrast_pairs[[i]]$name, ":top_10_pos")]] <- top_10_pos
  gene_sets$to_plot_full_ordered[[paste0(contrast_pairs[[i]]$name, ":ordered")]] <- full_ordered$gene_id

#  gene_sets$to_plot[[paste0(contrast_pairs[[i]]$name, ":top_10_neg")]] <- top_10_neg

}


```


```{r, CHD do test for phenotypes for each gene set}
hpo_onto <- ontos$hpo$ont
which <- which(hpo_onto$name=="Phenotypic abnormality")
major_systems <- hpo_onto$name[is.element(hpo_onto$id,hpo_onto$children[[which]])]

#major_systems <- c("Abnormal heart morphology","Abnormality of the musculature")
to_remove <- c("Constitutional symptom",
               "Abnormality of the thoracic cavity",
               "Abnormality of prenatal development or birth",
               "Neoplasm",
               "Abnormal cellular phenotype",
               "Growth abnormality")
major_systems <- major_systems[-which(is.element(major_systems,to_remove ))]
major_systems <- major_systems[grep("system",major_systems)]
major_systems <- list(system_name=major_systems,
                      descendent_ids=vector(mode="list",length=length(major_systems))  )
for(i in 1:length(major_systems$descendent_ids)){
  major_systems$descendent_ids[[i]] <- hpo_onto$descendants[[which(hpo_onto$name== major_systems$system_name[i] )]]
}


df <-  data.frame(ensembl_gene_id = character(),
                  omim_id = character(),
                  major_systems_affected = character(),
                  complexity  = numeric(),
                  chrom_subset_name = character())

synd_count_df <- data.frame(chrom_subset_name = character(),
                            num_disorders = numeric(),
                            num_genes = numeric() )
temp_gene_sets <- gene_sets$to_plot_full_ordered


  #list(chrom=gene_sets$human_chromatin_modifiers$gene_subsets$all_chrom_modifiers,
                   #    cilia=gene_sets$cilia$gene_subsets$cilium)
for(i in 1:length(temp_gene_sets)){
  chrom_subset <- temp_gene_sets[[i]]
  chrom_subset_name <- names(temp_gene_sets)[i]


  temp_map <- onto_maps$HPO_UBERON_GENE$map
  temp_map <- temp_map[is.element(temp_map$Ensembl_Gene_ID, chrom_subset),]
  temp_map <- temp_map[!temp_map$non_syndrome_flag,]

  for(temp_omim_id in unique(temp_map$OMIM_ID) ){
    temp_submap <- temp_map[which(temp_map$OMIM_ID==temp_omim_id),]
    major_systems_affected <- character()
    if(nrow(temp_submap)>0){
      for(j in 1:length(major_systems$system_name)){
        if(any(is.element(temp_submap$HPO_ID,major_systems$descendent_ids[[j]]))){
          major_systems_affected <- paste(c(major_systems_affected,
                                          major_systems$system_name[j]),collapse = ",")
        }
      }
    }
    if(length(major_systems_affected)==0){
      next
    }
    temp_df <- merge(data.frame(ensembl_gene_id = unique(temp_submap$Ensembl_Gene_ID)),data.frame(
                          omim_id = temp_omim_id,
                          major_systems_affected = strsplit(major_systems_affected,",")[[1]],
                          complexity = length(strsplit(major_systems_affected,",")[[1]]),
                          chrom_subset_name = chrom_subset_name))
    df <- rbind(df, temp_df)



  }
  synd_count_df <- rbind(synd_count_df,
                         data.frame(chrom_subset_name=chrom_subset_name,
                                    num_disorders=length(unique(temp_map$OMIM_ID)),
                                    num_genes=length(chrom_subset)))
}

#
# ggplot(unique(df[,c("omim_id","complexity","chrom_subset_name")]), aes(x=complexity))+
#   geom_bar()+
#   facet_grid(chrom_subset_name ~ . )+
#   theme(strip.text.y = element_text(angle = 0))
#
# filename <- paste0(dirs$figures, "_CHD_syndrome_complexity.png")
# ggsave(filename = filename, device="png",units="in",width=7,height=10,dpi=250)


df$chrom_subset_name <- str_remove(df$chrom_subset_name,":ordered")
df$chrom_subset_name <- factor(df$chrom_subset_name,
                               levels=c(
                                 "muscle v all",
                                 "striated muscle v other muscle",
                                 "cardiac muscle v other muscle",
                                 "skeletal muscle v other muscle",
                                 "smooth muscle v other muscle"))

synd_count_df$chrom_subset_name <- str_remove(synd_count_df$chrom_subset_name,":ordered")
synd_count_df$chrom_subset_name <- factor(synd_count_df$chrom_subset_name,
                                              levels=levels(df$chrom_subset_name))
levels(synd_count_df$chrom_subset_name) <- str_replace(levels(synd_count_df$chrom_subset_name),
                                                       " v ", "\nv ")
levels(df$chrom_subset_name) <- str_replace(levels(df$chrom_subset_name), " v ","\nv ")
df$system_name <- str_remove(str_remove(df$major_systems_affected,"Abnormality of "),"the ")
temp <- aggregate(df$system_name,by=list(df$system_name),FUN=length)
temp <- temp[order(temp$x,decreasing = T),]
df$system_name <- factor(df$system_name, levels = temp$Group.1)
levels(df$system_name) <- str_remove(levels(df$system_name)," system")

ggplot(df, aes(y=system_name, fill=system_name))+
  geom_bar()+
  geom_vline(data=synd_count_df, aes(xintercept=num_disorders),color="red",
             linetype="dotted")+
 # geom_vline(data=synd_count_df, aes(xintercept=num_genes),color="red")+
  scale_fill_grey()+
  facet_grid(chrom_subset_name ~ .)+
  theme_bw()+
  scale_y_discrete(limits=rev)+
  theme(strip.text.y = element_text(angle = 0),
        axis.text.x =  element_text(angle=45,hjust=0.95),
        legend.position="none")

filename <- paste0(dirs$figures, "_CHD_major_systems_affected.png")
ggsave(filename = filename, device="png",units="in",width=4.5,height=8,dpi=300)


### work on upset plot




```




```{r, setup heatmap}

onto <- ontos$uberon$ont
mat <- dataset_list$ENCODE_HH$agg_med_norm__mat
coldata <- dataset_list$ENCODE_HH$agg_med_norm__coldata

onto_names <- c("anatomical entity","muscle tissue","striated muscle tissue", "cardiac muscle tissue","skeletal muscle tissue","smooth muscle tissue")
temp_colgroups <- list("all not muscle" = setdiff(onto$ehh[[which(onto$name=="anatomical entity")]],onto$ehh[[which(onto$name=="muscle tissue")]]),
                       "cardiac muscle" = onto$ehh[[which(onto$name=="cardiac muscle tissue")]],
                       "skeletal muscle" = onto$ehh[[which(onto$name=="skeletal muscle tissue")]],
                       "smooth muscle" = onto$ehh[[which(onto$name=="smooth muscle tissue")]])

set.seed(2)
temp_colgroups$`all not muscle` <- sample(temp_colgroups$`all not muscle`,min(16,length(temp_colgroups$`all not muscle`)))
for(i in 2:length(temp_colgroups)){
  temp_colgroups[[i]] <- sample(temp_colgroups[[i]],min(8,length(temp_colgroups[[i]])))
}
temp_colgroups

temp_rows <- melt(gene_sets$to_plot)
temp_rows_names <- temp_rows$external_gene_name
temp_rows <- temp_rows$gene_id
temp_rows <- temp_rows[!is.na(temp_rows)]

temp_mat <- mat[temp_rows,unlist(temp_colgroups)]
colnames(temp_mat) <- make.unique(coldata$biosample_ontology.term_name[unlist(temp_colgroups)])
rownames(temp_mat) <- temp_rows_names

#temp_mat <- t(temp_mat)
ht <- Heatmap(
  temp_mat,
  row_order = 1:nrow(temp_mat),
  column_order = 1:ncol(temp_mat),
 # show_row_names = F
)
png(filename = paste0(dirs$figures,"temp_muscle_spec.png"), width = 7,height=10,units = "in",res=300)
draw(ht, padding = unit(c(0.9, 0.1, 0.1, 0.1), "in"))
dev.off()
  # heatmaps <- list()
  # for(type in c("delta", "flat", "weighted")){
  #   heatmaps[[type]] <- HeatmapList()
  #   for(measure in names(gene_list[["up"]])){
  #     spec_mat_name <- names(spec_mats)[intersect(grep(measure, names(spec_mats)), grep(type, names(spec_mats)))]
  #     spec_mat <-  spec_mats[[spec_mat_name ]]
  #     temp_name <- paste(spec_mat_name, sep="_")
  #     if(measure=="Zscore"){
  #       h1 <- Heatmap(spec_mat[gene_vec$gene,], name=temp_name,
  #                     row_order = gene_vec$gene, show_row_names = FALSE,
  #                     cluster_columns = sim_tree,
  #                     column_order = colnames(spec_mat),
  #                     col = col_funs[[paste(type,measure, sep="_")]])
  #     } else {
  #       h1 <- Heatmap(spec_mat[gene_vec$gene,], name=temp_name,
  #                     row_order = gene_vec$gene, show_row_names = FALSE,
  #                     col = col_funs[[paste(type,measure, sep="_")]])
  #     }
  #     if(length(heatmaps[[type]])==0){
  #       heatmaps[[type]] <- h1
  #     } else {
  #       heatmaps[[type]] <- heatmaps[[type]] + h1
  #     }
  #   }
  #   draw(heatmaps[[type]], padding = unit(c(0.9, 0.1, 0.3, 0.1), "in"))
  # }

```





```{r, chrom modifier specificity}
onto <- ontos$uberon$ont
mat <- dataset_list$ENCODE_HH$agg_med_norm__mat ### Specify chrom modifier gene set to look at

### want to perform clustering and reweighting using all genes
#mat <- mat[is.element(rownames(mat),gene_sets$human_chromatin_modifiers$gene_subsets$all_chrom_modifiers),]
coldata <- dataset_list$ENCODE_HH$agg_med_norm__coldata

major_anatomic_groups<- c("renal system",
                          "reproductive system",
                           "nervous system",
                           "cardiovascular system",
                           "musculoskeletal system",
                           "integumental system",
                           "immune system",
                           "digestive system",
                           "respiratory system",
                           "hematopoietic system",
                           "endocrine system")
## take some time to curate this to make clean 
coldata <- cbind(coldata, matrix(F, nrow=nrow(coldata), ncol=length(major_anatomic_groups),
       dimnames = list(rownames(coldata),major_anatomic_groups)) )
for( major_anatomic_group in major_anatomic_groups){
  coldata[onto$ehh[[which(onto$name==major_anatomic_group)]],major_anatomic_group] <- T 
}
View(coldata)

num_features <- nrow(mat)
onto$ehh_summary_stats <- vector("list", length(onto$id))
temp_stat_df_model <- data.frame(
  mean_internal = numeric(length=num_features),
  sd_internal = numeric(length=num_features),
  tau_internal = numeric(length=num_features),
  mean_external = numeric(length=num_features),
  sd_external = numeric(length=num_features),
  tau_external = numeric(length=num_features)
)
rownames(temp_stat_df_model) <- rownames(mat)

temp_els <- match( c("anatomical entity",
                     major_anatomic_groups),onto$name)

which_cols <- which( as.numeric(str_extract(coldata$age_group, "^[0-9]+")) >= 300 |
                       is.na(str_extract(coldata$age_group, "^[0-9]+")))

for(i in 1:length(temp_els)){
  ehh <- onto$ehh[[temp_els[i]]]
  onto$ehh_summary_stats[[temp_els[i]]] <- temp_stat_df_model

  for(set_and_complement in c(1,-1)){
  #  if(set_and_complement==1){print("set")} else {print("complement")}
    if(set_and_complement==1){temp_which_cols <- intersect(which_cols,ehh)}
    if(set_and_complement==-1){temp_which_cols <- setdiff(which_cols,ehh)}
    temp_mat <- mat[,temp_which_cols,drop=F]
    temp_coldata <- coldata[temp_which_cols,,drop=F]
    if(ncol(temp_mat)>0 & (length(ehh) > 2 | set_and_complement==1) ){
      colnames(temp_mat) <- make.unique(paste0(temp_coldata$biosample_ontology.term_name,
                                               ":",temp_coldata$age_group))
      if(ncol(temp_mat) > 2){
        dot_sim <- similarity_func(temp_mat)
        rownames(dot_sim) <- colnames(dot_sim) <- colnames(temp_mat)
        sim_tree <- cluster_func(dot_sim)
        weights <- get_weights(sim_tree, colnames(temp_mat))
        weighted_means <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.mean(x, weights=weights)})
        weighted_sds <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.var(x, weights=weights)})
        temp_tau <- calc_weighted_tau(temp_mat,weights)
      } else {
        weighted_means <- apply(temp_mat, MARGIN = 1, FUN = mean)
        weighted_sds <- NA
        temp_tau <- NA
      }
    } else {
      temp_tau <- NA
      weighted_means <- NA
      weighted_sds <- NA
    }
    if(set_and_complement==1){
      onto$ehh_summary_stats[[temp_els[i]]]$tau_internal <- temp_tau
      onto$ehh_summary_stats[[temp_els[i]]]$mean_internal <- weighted_means
      onto$ehh_summary_stats[[temp_els[i]]]$sd_internal <- weighted_sds
    } else {
      onto$ehh_summary_stats[[temp_els[i]]]$tau_external <- temp_tau
      onto$ehh_summary_stats[[temp_els[i]]]$mean_external <- weighted_means
      onto$ehh_summary_stats[[temp_els[i]]]$sd_external <- weighted_sds
    }

  }
}


#save.image("post_chrom_mod_specificity.RData")


major_systems_expr <- onto$ehh_summary_stats[temp_els]
names(major_systems_expr) <- onto$name[temp_els]
for(i in 1:length(major_systems_expr)){
colnames(major_systems_expr[[i]]) <- paste(names(major_systems_expr)[i],colnames(major_systems_expr[[i]]),sep=":")
}
major_systems_expr <- do.call("cbind", major_systems_expr)
temp_taus <- major_systems_expr[,grep("tau_internal", colnames(major_systems_expr))]

# df$specificity_state <- factor("complex",levels =c("specific","complex","ubiquitous") )
# df$specificity_state[which(df$tau_internal < 0.4)] <- "ubiquitous"
# df$specificity_state[which(df$tau_internal > 0.7)] <-  "specific"
# temp_names <- names(gene_sets$human_chromatin_modifiers$gene_subsets)


temp_which_cols <- intersect(which_cols, onto$ehh[[which(onto$name=="anatomical entity")]] )
temp_mat <- mat[,temp_which_cols,drop=F]
temp_coldata <- coldata[temp_which_cols,,drop=F]

colnames(temp_mat) <- make.unique(paste0(temp_coldata$biosample_ontology.term_name,
                                               ":",temp_coldata$age_group))
dot_sim <- similarity_func(temp_mat)
rownames(dot_sim) <- colnames(dot_sim) <- colnames(temp_mat)
sim_tree <- cluster_func(dot_sim)
weights <- get_weights(sim_tree, colnames(temp_mat))
weighted_means <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.mean(x, weights=weights)})
weighted_sds <- apply(temp_mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.var(x, weights=weights)})
weight_zscores <- calc_weighted_zscore_matrix(temp_mat,weights)

### for ms in major_systems
### which genes with tau_global > 0.5, have z_global > 1 stdev mean_global i.e. specific to particular system
### which genes with tau_global and NOT above condition have > 2 stdev mean_global i.e. specifc to particular biosample
### stdev sensative to small changes in genes with very low variance - want more magnitude of change to select on e.g. log(fc)  
### NOTE: log(x)-log(y) == log(x/y)
major_system_gene_sets <- list()
biosample_gene_sets <- list()
cutoff_sys2global_z = 1
cutoff_sys2global_abs_delta_log10 = log10(1.5) ## i.e. at least a 50% diff in expression
cutoff_point2global_z = 2
cutoff_point2global_abs_delta_log10 = log10(2) ## i.e. at least 2x diff
cutoff_min_expr = log10(2.5) ## log10(5 TPM) ~ doesn't account for median normalization but if factor close to 1 for most this is ok 

global_means <- major_systems_expr$`anatomical entity.anatomical entity:mean_internal`
global_sds <- major_systems_expr$`anatomical entity.anatomical entity:sd_internal`
global_taus <- major_systems_expr$`anatomical entity.anatomical entity:tau_internal`
names(global_taus) <- names(global_means) <- names(global_sds) <- rownames(major_systems_expr)
for( i in 1:length(major_anatomic_groups)){
  major_anatomic_group <- major_anatomic_groups[i]
  temp_means <- major_systems_expr[[grep(paste0(major_anatomic_group,".*mean_internal"), names(major_systems_expr))]]
  temp_zs <- (temp_means - global_means) / global_sds
  
  which <- which(
    ((temp_zs) > cutoff_sys2global_z) &
    ((temp_means - global_means) > cutoff_sys2global_abs_delta_log10) &
    (temp_means > cutoff_min_expr ) & # | global_means > cutoff_min_expr) &
    (is.element(rownames(major_systems_expr),gene_sets$human_chromatin_modifiers$gene_subsets$all_chrom_modifiers)) &
    (global_taus > 0.7)
  )
  
  major_system_gene_sets[[major_anatomic_group]] <- gene_sets$genes_all[match(rownames(major_systems_expr)[which],gene_sets$genes_all$ensembl_gene_id),
                      c("external_gene_name","ensembl_gene_id")]
  major_system_gene_sets[[major_anatomic_group]] <- cbind(major_system_gene_sets[[major_anatomic_group]],data.frame(biosample="full_system")) 
  ids_in_major_system <- rownames(major_systems_expr)[which]
  for(j in which(temp_coldata[[major_anatomic_group]])){
    temp_coldata[j,]
     
    which <- which(
      ((weight_zscores[,j]) > cutoff_point2global_z) &
      ((temp_mat[,j] - global_means) > cutoff_point2global_abs_delta_log10) &
      (temp_mat[,j] > cutoff_min_expr ) & # | global_means > cutoff_min_expr) &
      (is.element(rownames(major_systems_expr),gene_sets$human_chromatin_modifiers$gene_subsets$all_chrom_modifiers)) &
      (global_taus > 0.7)
    )
    if(length(which)==0){next}
    temp_df <- cbind(gene_sets$genes_all[match(rownames(major_systems_expr)[which],gene_sets$genes_all$ensembl_gene_id),
                                         c("external_gene_name","ensembl_gene_id")],
                  data.frame(biosample = paste0(temp_coldata$biosample_ontology.term_name[j],".",j) ))
    which <- which(!is.element(temp_df$ensembl_gene_id,ids_in_major_system))
    if(length(which)==0){next}
    temp_df <- temp_df[which,]
    major_system_gene_sets[[major_anatomic_group]] <- rbind(major_system_gene_sets[[major_anatomic_group]], temp_df)
  }
  
}

for(i in 1:length(major_system_gene_sets)){
  major_system_gene_sets[[i]]$is_full_system <- major_system_gene_sets[[i]]$biosample == "full_system"
  major_system_gene_sets[[i]]$sys_or_subset <- ifelse(major_system_gene_sets[[i]]$is_full_system,
                                                       names(major_system_gene_sets)[i],
                                                       paste0(names(major_system_gene_sets)[i]," subset") )
}

simplified_major_system_gene_set_df <- NULL
temp_colnames_in_order <- c()
temp_sytemnames_in_order <- c()
for(i in 1:length(major_system_gene_sets)){
  simplified_major_system_gene_set_df <- rbind(simplified_major_system_gene_set_df,
                                               unique(major_system_gene_sets[[i]][,c("external_gene_name","ensembl_gene_id","sys_or_subset")]))
  temp_colnames <- paste0(temp_coldata$biosample_ontology.term_name,":",
                                     temp_coldata$age_group)[which(temp_coldata[names(major_system_gene_sets)[i]][[1]])]
  temp_colnames_in_order <- c(temp_colnames_in_order, temp_colnames)
  temp_sytemnames_in_order <- c(temp_sytemnames_in_order, rep(names(major_system_gene_sets)[i], length(temp_colnames)))
}

simplified_major_system_gene_set_df <- simplified_major_system_gene_set_df[!grepl("^H[0-9]",
                                                                                  simplified_major_system_gene_set_df$external_gene_name),]


temp_rownames_in_order <- simplified_major_system_gene_set_df$ensembl_gene_id
temp <- gene_sets$genes_all$external_gene_name[match(temp_rownames_in_order, gene_sets$genes_all$ensembl_gene_id) ]
temp[which(temp=="")] <- temp_rownames_in_order[which(temp=="")]
temp_rownames_in_order <- temp
#temp_mat[temp_rownames_in_order,temp_colnames_in_order]
temp <- gene_sets$genes_all$external_gene_name[match(rownames(temp_mat), gene_sets$genes_all$ensembl_gene_id) ]
temp[which(temp=="")] <- rownames(temp_mat)[which(temp=="")]
rownames(temp_mat) <- temp

dend1 <- cluster_within_group(temp_mat[temp_rownames_in_order,
                                       temp_colnames_in_order] ,
                              factor(temp_sytemnames_in_order, levels = unique(temp_sytemnames_in_order)))

png(filename=paste0(dirs$figures,"heatmap_test_order_by_system.png"), height = 30,width=24,res = 280,unit="in")
Heatmap(t(temp_mat[temp_rownames_in_order, temp_colnames_in_order]), cluster_columns = F, cluster_rows = F) #dend1)
dev.off()

png(filename=paste0(dirs$figures,"heatmap_test_order_by_system_cluster_in_system.png"), height = 30,width=24,res = 280,unit="in")
Heatmap(t(temp_mat[temp_rownames_in_order, temp_colnames_in_order]), cluster_columns = F, cluster_rows = dend1)
dev.off()

png(filename=paste0(dirs$figures,"heatmap_test_order_by_system_cluster_in_system_and_genes.png"), height = 30,width=24,res = 280,unit="in")
Heatmap(t(temp_mat[temp_rownames_in_order, temp_colnames_in_order]), cluster_columns = T, cluster_rows = dend1)
dev.off()

png(filename=paste0(dirs$figures,"heatmap_test_order_in_system_and_genes.png"), height = 30,width=24,res = 280,unit="in")
Heatmap(t(temp_mat[temp_rownames_in_order, temp_colnames_in_order]), cluster_columns = T, cluster_rows = T)
dev.off()

#### for each specific gene
##### find onto concept(s) that match greatest number of tissues with specific expression for that gene - add to temp_col_order w info r.e. onto concept used

spec_genes <- names(global_taus)[which(global_taus > 0.7)]
spec_genes <- spec_genes[which(is.element(spec_genes, gene_sets$human_chromatin_modifiers$gene_subsets$all_chrom_modifiers))]

spec_biosamples <- list()
for(g in spec_genes){
  spec_biosamples[[g]] <- list(colnames = colnames(weight_zscores[g, which(weight_zscores[g,] > 2),drop=F]))
  spec_biosamples[[g]]$colids_spec <- which(
    is.element(paste0(coldata$biosample_ontology.term_name,":",coldata$age_group),
               spec_biosamples[[g]]$colnames))
  spec_biosamples[[g]]$colids_not_spec <- which(
    is.element(paste0(coldata$biosample_ontology.term_name,":",coldata$age_group),
               colnames(temp_mat) ))
  spec_biosamples[[g]]$colids_not_spec <- setdiff(spec_biosamples[[g]]$colids_not_spec, spec_biosamples[[g]]$colids_spec)
  
  temp_df <- data.frame(id=onto$id, name=onto$name, num_colids=0, num_not_colids=0)
  for(i in 1:length(onto$ehh)){
    ehh <- onto$ehh[[i]]
    if(length(ehh)==0){next}
    temp_df$num_colids[i] <- sum(is.element(spec_biosamples[[g]]$colids_spec, ehh))
    temp_df$num_not_colids[i] <- sum(is.element(spec_biosamples[[g]]$colids_not_spec, ehh))
  }
  temp_df$prop_spec <- temp_df$num_colids / (temp_df$num_colids + temp_df$num_not_colids)
  temp_df <- temp_df[which( #temp_df$prop_spec == max(c(0.1, temp_df$prop_spec), na.rm = T) |
                            temp_df$prop_spec > 0.3 ) ,]
  temp_df <- temp_df[which(temp_df$num_colids > 1 ) ,]
  
  # temp_df <- temp_df[which(temp_df$num_colids == max(temp_df$num_colids, na.rm = T) |
  #                            temp_df$num_colids > 3) ,]
  spec_biosamples[[g]]$uberon_subtable <- temp_df
}



sink(file=paste0(dirs$results,"spec_biosamples.txt"))
for(i in 1:length(spec_biosamples)){
  print(paste0(i,":",names(spec_biosamples)[i]))
  print(gene_sets$genes_all$external_gene_name[which(gene_sets$genes_all$ensembl_gene_id==names(spec_biosamples)[i])])
  print("number of columns specific:")
  print(length(spec_biosamples[[i]]$colids_spec));print(spec_biosamples[[i]]$colnames) 
  print(spec_biosamples[[i]]$uberon_subtable);print("");print("")}
sink()
 

 
weight_zscores[spec_genes,]
```

```{r, chrom modifier specificity/ubiquity plot}

df <- onto$ehh_summary_stats[[which(onto$name=="anatomical entity")]]
df$specificity_state <- factor("complex",levels =c("specific","complex","ubiquitous") )
df$specificity_state[which(df$tau_internal < 0.4)] <- "ubiquitous"
df$specificity_state[which(df$tau_internal > 0.7)] <-  "specific"
temp_names <- names(gene_sets$human_chromatin_modifiers$gene_subsets)
#temp_names <- temp_names[which(temp_names != "chromatin looping")]
df_out <- merge(temp_names,
                c("specific","complex","ubiquitous"))
colnames(df_out) <- c("gene_subset","expr_class")
df_out$proportion <- 0

full_df <- data.frame()
for(i in 1:length(gene_sets$human_chromatin_modifiers$gene_subsets)){
  gene_set_name <- names(gene_sets$human_chromatin_modifiers$gene_subsets)[i]
  which <- which(is.element(rownames(df),
                      gene_sets$human_chromatin_modifiers$gene_subsets[[i]]))
  if(length(which)==0){next}
  temp_df <- df[which,,drop=F]
  temp_df <- temp_df[order(temp_df$tau_internal,decreasing = F),,drop=F]
  temp_df$index <- 1:nrow(temp_df)
  gg <- ggplot(temp_df, aes(index,tau_internal )) +
    geom_point()+
    ggtitle(gene_set_name)+
    scale_y_continuous(limits = c(0,1),breaks=seq(0,1,by=0.1))+
    scale_x_continuous(
      "number of chromatin modifiers",
      sec.axis = sec_axis(~ . / nrow(temp_df), name = "proportion",breaks=seq(0,1,by=0.1))
    )
  plot(gg)

  which <- which(df_out$gene_subset==gene_set_name & df_out$expr_class=="specific")
  df_out$proportion[which] <- length(which(temp_df$specificity_state=="specific")) / nrow(temp_df)
  which <- which(df_out$gene_subset==gene_set_name & df_out$expr_class=="complex")
  df_out$proportion[which] <- length(which(temp_df$specificity_state=="complex")) / nrow(temp_df)
  which <- which(df_out$gene_subset==gene_set_name & df_out$expr_class=="ubiquitous")
  df_out$proportion[which] <- length(which(temp_df$specificity_state=="ubiquitous")) / nrow(temp_df)

  temp_df$index_proportion <- temp_df$index / nrow(temp_df)
  temp_df$num_modifiers <- nrow(temp_df)
  temp_df$gene_name <- rownames(temp_df)
  full_df <- rbind(full_df, cbind(temp_df,data.frame(gene_subset=gene_set_name)))
}

ggplot(full_df, aes(index_proportion,tau_internal,color=specificity_state))+
  geom_point()+
   theme(strip.text.x = element_text(size = 6))+
  #scale_y_continuous(limits = c(0,1),breaks=seq(0,1,by=0.2))+
  facet_wrap(. ~ gene_subset, nrow=3)
ggsave(filename=paste0(dirs$figures,"temp_specificity_distribution_color.png"), height=6,width=8,units = "in",device = "png")

df_out$gene_subset
df_out$gene_subset <- factor(df_out$gene_subset)
df_out$expr_class <- factor(df_out$expr_class, levels=c("specific","complex","ubiquitous"))
ggplot(df_out, aes(gene_subset, proportion, fill=expr_class))+
  geom_bar(position="fill", stat="identity")+
  scale_x_discrete(limits=rev(levels(df_out$gene_subset)))+
  coord_flip()
ggsave(filename=paste0(dirs$figures,"temp_specificity_dist_simplified.png"), height=8,width=6,units = "in",device = "png")
#
# 343
# ggl[["inheritance"]] <- ggplot(df, aes(x=inheritance, fill=prob, y=prop))+
#   geom_col(stat="identity", position=position_identity(), width = 0.99,)+
#   scale_fill_manual(values=c("lightblue1","lightblue2","lightblue3","lightblue4","grey30","grey20"))+
#   theme_classic()+
#   theme(strip.text.y = element_text(angle = 0))+
#   facet_grid(chrom_subset_name ~ .)

```

```{r, chrom modifier specificity}
onto <- ontos$uberon$ont
temp_el <- grep("^anatomical entity$",onto$name)
ehh <- onto$ehh[[temp_el]]

mat <- dataset_list$ENCODE_HH$agg_med_norm__mat[,ehh] 
mat <- mat[is.element(rownames(mat),gene_sets$human_chromatin_modifiers$gene_subsets$all_chrom_modifiers),]
coldata <- dataset_list$ENCODE_HH$agg_med_norm__coldata[ehh,]
rm(ehh)


mat <- mat[,which(as.numeric(str_remove(coldata$age_group, "-.*")) > 512 |
                    coldata$age_group == "")]
coldata <- coldata[which(as.numeric(str_remove(coldata$age_group, "-.*")) > 512 |
                    coldata$age_group == ""),]
colnames(mat) <- paste0(coldata$biosample_ontology.term_name,
                        coldata$age_group)

coldata$mat_colnames <- paste(coldata$assay_term_name,
                                   coldata$biosample_ontology.term_name,
                                   coldata$age_group,sep=":")


major_anatomic_groups <- c("genitourinary system",
                           "nervous system",
                           "cardiovascular system",
                           "musculoskeletal system",
                           "integumental system",
                           "immune system",
                           "digestive system",
                           "respiratory system",
                           "hematopoietic system",
                           "endocrine system",
                           "limb")
coldata$major_anatomic_group <- ""
for(i in 1:nrow(coldata)){
  coldata$biosample_ontology
  
  which <- ontos$uberon$ont$ehh[[which(ontos$uberon$ont$name==anatomic_group)]]
  coldata$major_anatomic_group[which] <- str_remove(paste(coldata$major_anatomic_group[which],
                                                    str_remove(anatomic_group," system"),sep=","),"^,") 
}



num_features <- nrow(mat)
spec_ss <- list()



dot_sim <- similarity_func(mat)
rownames(dot_sim) <- colnames(dot_sim) <- colnames(mat)
sim_tree <- cluster_func(dot_sim)
weights <- get_weights(sim_tree, colnames(mat))
spec_ss$mean <- apply(mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.mean(x, weights=weights)})
spec_ss$sd <- apply(mat, MARGIN = 1, FUN = function(x){Hmisc::wtd.var(x, weights=weights)})
spec_ss$tau <- calc_weighted_tau(mat,weights)
spec_ss$zscore <- calc_weighted_zscore_matrix(mat,weights)
spec_ss$zscore[is.na(spec_ss$zscore)] <- 0







save.image("post_spec.RData")
```



```{r, ubiquitous-complex-specific heatmaps}
table(df$specificity_state) 

hist(df$mean_internal[which(df$specificity_state=="ubiquitous")], xlim = c(0,max(df$mean_internal)),
     breaks=100)
hist(df$mean_internal[which(df$specificity_state=="complex")], xlim = c(0,max(df$mean_internal)),
     breaks=100)
hist(df$mean_internal[which(df$specificity_state=="specific")], xlim = c(0,max(df$mean_internal)),
     breaks=100)

mat <- dataset_list$ENCODE_HH$agg_med_norm__mat
mat <- mat[is.element(rownames(mat),rownames(df)),]
coldata <- dataset_list$ENCODE_HH$agg_med_norm__coldata
colnames(mat) <- coldata$biosample_ontology.term_name
mat <- mat[,which(as.numeric(str_remove(coldata$age_group, "-.*")) > 512 |
                    coldata$age_group == "")]

heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="ubiquitous")]),], scale="row")
heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="ubiquitous")]),], scale="column")
heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="ubiquitous")]),], scale="none")


heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="complex")]),], scale="row")
heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="complex")]),], scale="column")
heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="complex")]),], scale="none")


heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="specific")]),], scale="row")
heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="specific")]),], scale="column")
heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="specific")]),], scale="none")


Heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="ubiquitous")]),])
Heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="complex")]),])
Heatmap(mat[is.element(rownames(mat),rownames(df)[which(df$specificity_state=="specific")]),])


b
```


```{r, chrom modifier specificity map to specific onto term for specific chrom modifiers}

for(i in 1:length(onto$ehh_summary_stats)){
  if(is.null(onto$ehh_summary_stats[[i]])){next}
  onto$ehh_summary_stats[[i]]$delta_mean <- onto$ehh_summary_stats[[i]]$mean_internal - onto$ehh_summary_stats[[i]]$mean_external
}

temp_df <- full_df[which(full_df$gene_subset=="all_chrom_modifiers" &
                           (full_df$specificity_state=="specific" | full_df$specificity_state=="complex") ),]


temp_onto_ids <- which(onto$ehh_num_cols > 5 & onto$ehh_num_cols < 80)
temp_genes <- unique(temp_df$gene_name)
delta_mean_df <- matrix(nrow=length(temp_genes),ncol=length(temp_onto_ids),dimnames=list(temp_genes,temp_onto_ids))
delta_mean_df <- matrix(nrow=length(temp_genes),ncol=length(temp_onto_ids),dimnames=list(temp_genes,temp_onto_ids))

for(i in temp_onto_ids){
  delta_mean_df[,as.character(i)] <- onto$ehh_summary_stats[[i]][temp_genes,]$delta_mean
}

rownames(delta_mean_df) <- gene_sets$genes_all$external_gene_name[match(rownames(delta_mean_df),
                                                                        gene_sets$genes_all$ensembl_gene_id)]
colnames(delta_mean_df) <- onto$name[temp_onto_ids]

png(filename=paste0(dirs$figures,"temp_heatmap_onto_spec_chrom.png"),width=14,height=14,units="in",res=250)
heatmap(t(delta_mean_df),scale="none",
        margins = c(4,12)
        )
legend(x="bottomleft",legend=c("min","ave","max"),
       fill=rev(heat.colors(3)))
dev.off()


```

```{r, chrom modifier specificity map to specific onto term for specific chrom modifiers}



```


