---
title: "gtex_heatmap"
output: html_document
---
```{r libraries}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(ComplexHeatmap)
library("circlize")
library("RColorBrewer")
library(igraph)

```
```{r read table}
gtex <- read.csv("~/Downloads/gtex_medians_PC_only_wo_MT.csv", header=TRUE)
```
```{r clean table}
View(gtex)
#remove first column of gtex
gtex <- gtex[,-c(1)]
#name+description table
gene_id_to_name <- gtex[,c(1,2)]
View(gene_id_to_name)
rownames(gtex) <- gtex$Name
gtex <- gtex[,-c(1) ]
#gives ensemble id of duplicated gene names
gtex$V1[which(duplicated(gtex$V2))]

```
```{r names in gtex}
#look for gene names in gtex
kmt2 <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 2))
kdm <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 3))
kat <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 4))
hdac <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 5))

modifier_table <- filter(gtex, Description %in% kmt2| Description %in% kdm|Description %in% kat|Description %in% hdac)

modifier_mx <- apply(as.matrix(modifier_table, ncol= ncol(modifier_table)), 2, as.numeric)
modifier_mx <- modifier_mx[,-c(1)]
modifier_mx[is.na(modifier_mx)] <- 0
rownames(modifier_mx) <- modifier_table$Description

```

```{r specificity heatmap for all}
modifier_sd <- modifier_mx

for(i in 1:nrow(modifier_mx)){
 modifier_sd[i,] <- (modifier_mx[i,]- mean(modifier_mx[i,]))/(sd(modifier_mx[i,]))
}
modifier_sd[is.na(modifier_sd)] <- 0
rownames(modifier_sd) <- modifier_table$Description
```
```{r heatmap of sd}
#plot of sd
Heatmap(modifier_sd, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 4), width = unit(12, "cm"), height = unit(8, "cm"))

```
```{r create binary matrix}
modifier_sd <- t(modifier_sd)
Type <- vector(length= ncol(modifier_sd))
modifier_sd2 <- rbind(modifier_sd, Type)

for(i in 1:ncol(modifier_sd2)) {
  if (colnames(modifier_sd2)[i] %in% kmt2) {modifier_sd2["Type", i]= "KMT"}
  else if (colnames(modifier_sd2)[i] %in% kdm) {modifier_sd2["Type", i]= "KDM"}
  else if (colnames(modifier_sd2)[i] %in% kat) {modifier_sd2["Type", i]= "KAT"}
  else {modifier_sd2["Type", i]= "HDAC"}
}

binary <- modifier_sd
binary[binary<2] <- 0
binary[binary>=2] <- 1
binary.cor <- cor(binary, method= "pearson")
binary.cor[is.na(binary.cor)] <- 0

```
```{r heatmap of binary}
#plot of sd
png(filename= "binary_specificity.png", res=300, width=3000, height=3000)
Heatmap(binary.cor, name="SD>2", column_names_gp = grid::gpar(fontsize = 5), row_names_gp = grid::gpar(fontsize = 5))
dev.off()

```
```{r color palette}
#color levels
coul <- brewer.pal(nlevels(as.factor(modifier_sd2["Type",])), "Set2")
my.color <- coul[as.numeric(as.factor(modifier_sd2["Type",]))]
```
```{r network plot}
#Remove lower correlations
network.mx <- binary.cor
network.mx[network.mx<0.9] <- 0
#igraph object from matrix
network1 <- graph_from_adjacency_matrix(network.mx, weighted=T, mode="undirected", diag=F)
par(bg="grey13", mar=c(0,0,0,0))
plot(network1, vertex.size= 5, vertex.label.cex=0.3, vertex.color=my.color, vertex.label.color="white", vertex.frame.color="transparent")
#legend
legend(x=1.2, y=-0.4, legend=paste(levels(as.factor(modifier_sd2["Type",]))), col = coul, bty = "n", pch=20 , pt.cex = 2, cex=1, text.col="white", horiz = F)
```
```{r png}
png(filename= "network_binary_0.9.png", res=300, width=3000, height=3000)
network1 <- graph_from_adjacency_matrix(network.mx, weighted=T, mode="undirected", diag=F)
par(bg="grey13", mar=c(0,0,0,0))
plot(network1, vertex.size= 5, vertex.label.cex=0.3, vertex.color=my.color, vertex.label.color="white", vertex.frame.color="transparent")
#legend
legend(x=1.2, y=-0.4, legend=paste(levels(as.factor(modifier_sd2["Type",]))), col = coul, bty = "n", pch=20 , pt.cex = 2, cex=1, text.col="white", horiz = F)
dev.off()

```








