---
title: "HPA + GTEX"
output: html_document
---

```{r document}
#Spearman correlation of HPA protein levels for modifiers (originally did Pearson's and got about the same correlations)

#pairwise Pearson correlations for subcategories of modifiers (using original HPA tissues)

#network plot for HPA correlations (Spearman, originally Pearson)

#heatmap of distribution of protein levels by gene (resolution heatmap)

#specificity heatmap for all modifiers in HPA

#network plot for specificity (Spearman's correlation for protein specificity matrix, then network)

#specificity heatmap for each modifier subcategory (using OG HPA tissues)

#Heatmap of modifier protein levels when grouped by tissues and when grouped by cell type

```
```{r libraries}
library(matrixStats)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library("Hmisc")
library(ComplexHeatmap)
library("circlize")
library("RColorBrewer")
library(gdata)
library(igraph)

```


```{r read in data}
HPA_tissue_exp <- read.delim("~/Downloads/HPA_tissue_exp.tsv")

#read in modifier lists
kmt <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 2))
kdm <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 3))
kat <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 4))
hdac <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 5))


```

```{r modify HPA}
#convert detection levels to numbers
HPA_exp <- HPA_tissue_exp
for(i in 1:length(HPA_exp$Level)) {
        if (HPA_exp$Level[i] == "Not detected") {
HPA_exp$Level[i]=0
        } 
    else if (HPA_exp$Level[i]== "Low") {
HPA_exp$Level[i]=1
    } 
    else if (HPA_exp$Level[i]== "Medium") {
HPA_exp$Level[i]=2
    } 
    else {
HPA_exp$Level[i]=3
} 
}

HPA_exp$Level <- as.numeric(HPA_exp$Level)
HPA_exp2 <- HPA_exp
HPA_exp <- HPA_exp[,-c(1,4,6)]
hist(HPA_exp$Level)

```


```{r filter for modifiers in HPA exp}
#filter for kmt
HPA_filter <- filter(HPA_exp, Gene.name %in% kmt| Gene.name %in% kdm| Gene.name %in% kat| Gene.name %in% hdac)

HPA_filter2 <- HPA_filter %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique()
HPA_filter2 <- HPA_filter2 %>% pivot_wider(names_from= Tissue, values_from= Level)
HPA_filter2 <- data.frame(HPA_filter2)
rownames(HPA_filter2) <- HPA_filter2$Gene.name
HPA_filter2 <- HPA_filter2[,-c(1)]
HPA_filter2[is.na(HPA_filter2)] <- 0

```
```{r correlation matrix}
HPA_filter2 <- t(HPA_filter2)
Type <- vector(length= ncol(HPA_filter2))
HPA_filter3 <- rbind(HPA_filter2, Type)

for(i in 1:ncol(HPA_filter3)) {
  if (colnames(HPA_filter3)[i] %in% kmt) {HPA_filter3["Type", i]= "KMT"}
  else if (colnames(HPA_filter3)[i] %in% kdm) {HPA_filter3["Type", i]= "KDM"}
  else if (colnames(HPA_filter3)[i] %in% kat) {HPA_filter3["Type", i]= "KAT"}
  else {HPA_filter3["Type", i]= "HDAC"}
}



HPA.cor <- cor(HPA_filter2, method="spearman")
HPA.cor[is.na(HPA.cor)] <- 0
```
```{r heatmap}
png("all_modifier_HPA_cor_sp.png", res=300, width= 3000, height=3000)
Heatmap(HPA.cor, name= "Score", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 7), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()


```
```{r pairwise correlations}
HPA_filter_df <- data.frame(t(HPA_filter2))

kmt_hpa2 <- t(filter(HPA_filter_df, rownames(HPA_filter_df) %in% kmt))
kdm_hpa2 <- t(filter(HPA_filter_df, rownames(HPA_filter_df) %in% kdm))
kat_hpa2 <- t(filter(HPA_filter_df, rownames(HPA_filter_df) %in% kat))
hdac_hpa2 <- t(filter(HPA_filter_df, rownames(HPA_filter_df) %in% hdac))

kmt.hpa.cor <- cor(kmt_hpa2, method= "pearson")
kmt.hpa.cor[is.na(kmt.hpa.cor)] <- 0

kdm.hpa.cor <- cor(kdm_hpa2, method= "pearson")
kdm.hpa.cor[is.na(kdm.hpa.cor)] <- 0

kat.hpa.cor <- cor(kat_hpa2, method= "pearson")
kat.hpa.cor[is.na(kat.hpa.cor)] <- 0

hdac.hpa.cor <- cor(hdac_hpa2, method= "pearson")
hdac.hpa.cor[is.na(hdac.hpa.cor)] <- 0

kmt.kdm.cor <- cor(kmt_hpa2, kdm_hpa2, method= "pearson")
kmt.kdm.cor[is.na(kmt.kdm.cor)] <- 0

kmt.kat.cor <- cor(kmt_hpa2, kat_hpa2, method= "pearson")
kmt.kat.cor[is.na(kmt.kat.cor)] <- 0

kmt.hdac.cor <- cor(kmt_hpa2, hdac_hpa2, method= "pearson")
kmt.hdac.cor[is.na(kmt.hdac.cor)] <- 0

kdm.kat.cor <- cor(kdm_hpa2, kat_hpa2, method= "pearson")
kdm.kat.cor[is.na(kdm.kat.cor)] <- 0

kdm.hdac.cor <- cor(kdm_hpa2, hdac_hpa2, method= "pearson")
kdm.hdac.cor[is.na(kdm.hdac.cor)] <- 0

kat.hdac.cor <- cor(kat_hpa2, hdac_hpa2, method= "pearson")
kat.hdac.cor[is.na(kat.hdac.cor)] <- 0


```
```{r png}
png("kmt_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kmt.hpa.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

```
```{r png}
png("kdm_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kdm.hpa.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

```
```{r png}
png("kat_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kat.hpa.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

png("hdac_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(hdac.hpa.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 10), row_names_gp = grid::gpar(fontsize = 10), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

```
```{r png}
png("kmt_kdm_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kmt.kdm.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

png("kmt_kat_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kmt.kat.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

png("kmt_hdac_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kmt.hdac.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

png("kdm_kat_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kdm.kat.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

png("kdm_hdac_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kdm.hdac.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()

png("kat_hdac_hpa_cor2.png", res=300, width= 3000, height=3000)
Heatmap(kat.hdac.cor, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, column_names_gp = grid::gpar(fontsize = 9), row_names_gp = grid::gpar(fontsize = 9), col = colorRamp2(c(-1, -0.8, -0.5, 0, 0.5, 0.8, 1), brewer.pal(n=7, name="PRGn")))
dev.off()


```
```{r color palette}
#color levels
coul <- brewer.pal(nlevels(as.factor(HPA_filter3["Type",])), "Set2")
my.color <- coul[as.numeric(as.factor(HPA_filter3["Type",]))]
```
```{r network plot}
#Remove lower correlations
network.mx2 <- HPA.cor
network.mx2[network.mx2<0.65] <- 0
#igraph object from matrix
network2 <- graph_from_adjacency_matrix(network.mx2, weighted=T, mode="undirected", diag=F)
par(bg="grey13", mar=c(0,0,0,0))
plot(network2, vertex.size= 5, vertex.label.cex=0.3, vertex.color=my.color, vertex.label.color="white", vertex.frame.color="transparent")
#legend
legend(x=1.2, y=-0.4, legend=paste(levels(as.factor(HPA_filter3["Type",]))), col = coul, bty = "n", pch=20 , pt.cex = 2, cex=1, text.col="white", horiz = F)
```
```{r png}
png(filename= "network_HPA_0.65_sp.png", res=300, width=3000, height=3000)
network2 <- graph_from_adjacency_matrix(network.mx2, weighted=T, mode="undirected", diag=F)
par(bg="grey13", mar=c(0,0,0,0))
plot(network2, vertex.size= 5, vertex.label.cex=0.35, vertex.color=my.color, vertex.label.color="white", vertex.frame.color="transparent")
#legend
legend(x=1.2, y=-0.4, legend=paste(levels(as.factor(HPA_filter3["Type",]))), col = coul, bty = "n", pch=20 , pt.cex = 2, cex=1, text.col="white", horiz = F)
dev.off()

```


```{r resolution}
HPA_round <- HPA_filter2

for(row in 1:nrow(HPA_round)) {
  for(col in 1:ncol(HPA_round)) {
        if (HPA_round[row,col] >= 2.5) {
HPA_round[row,col]=3
} 
    else if (HPA_round[row,col] < 2.5 & HPA_round[row,col] >= 1.5) {
HPA_round[row,col]=2
    } 
    else if (HPA_round[row,col] < 1.5 & HPA_round[row,col] >= 0.5) {
HPA_round[row,col]=1
} 
    else {
HPA_round[row,col]=0
}
  }}

res <- table(c(col(HPA_round)), c(HPA_round))
resm <- rbind(as.numeric(names(res)), res)
rownames(resm) <- colnames(HPA_round)

png(filename= "HPA_expression_counts2", res=300, width= 1000, height=3000)
Heatmap(resm, name= "count", row_names_side= "right", row_dend_side= "left", cluster_columns= FALSE, row_names_gp = grid::gpar(fontsize = 6), col = colorRamp2(c(0,10,20,30,40,50), brewer.pal(n=6, name="Blues")))
dev.off()


```
```{r specificity heatmap for all hpa}
HPA_filter_z <- t(HPA_filter2)

for(i in 1:nrow(HPA_filter_z)){
 HPA_filter_z[i,] <- (HPA_filter_z[i,]- mean(HPA_filter_z[i,]))/(sd(HPA_filter_z[i,]))
}
HPA_filter_z[is.na(HPA_filter_z)] <- 0

# Open a png file
png("all_hpa_z.png", res=300, width=3000, height=3000) 
# 2. Create a plot
Heatmap(HPA_filter_z, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(15, "cm"))
# Close the pdf file
dev.off() 

```


```{r network plot for specificity}
HPA.z.cor <- cor(t(HPA_filter_z), method="spearman")
HPA.z.cor[is.na(HPA.z.cor)] <- 0

#Remove lower correlations
network.mx3 <- HPA.z.cor
network.mx3[network.mx3<0.65] <- 0
#igraph object from matrix
network3 <- graph_from_adjacency_matrix(network.mx3, weighted=T, mode="undirected", diag=F)
par(bg="grey13", mar=c(0,0,0,0))
plot(network3, vertex.size= 5, vertex.label.cex=0.3, vertex.color=my.color, vertex.label.color="white", vertex.frame.color="transparent")
#legend
legend(x=1.2, y=-0.4, legend=paste(levels(as.factor(HPA_filter3["Type",]))), col = coul, bty = "n", pch=20 , pt.cex = 2, cex=1, text.col="white", horiz = F)
```
```{r png}
png(filename= "network_HPA_specificity_0.65_sp.png", res=300, width=3000, height=3000)
network3 <- graph_from_adjacency_matrix(network.mx3, weighted=T, mode="undirected", diag=F)
par(bg="grey13", mar=c(0,0,0,0))
plot(network3, vertex.size= 5, vertex.label.cex=0.35, vertex.color=my.color, vertex.label.color="white", vertex.frame.color="transparent")
#legend
legend(x=1.2, y=-0.4, legend=paste(levels(as.factor(HPA_filter3["Type",]))), col = coul, bty = "n", pch=20 , pt.cex = 2, cex=1, text.col="white", horiz = F)
dev.off()

```

```{r specificity heatmap for hpa exp kmt}
kmt.hpa.z <- t(kmt_hpa2)

for(i in 1:nrow(kmt.hpa.z)){
 kmt.hpa.z[i,] <- (kmt.hpa.z[i,]- mean(kmt.hpa.z[i,]))/(sd(kmt.hpa.z[i,]))
}
kmt.hpa.z[is.na(kmt.hpa.z)] <- 0

# Open a png file
png("kmt_hpa_z.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(kmt.hpa.z, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r specificity heatmap for hpa exp kdm}
kdm.hpa.z <- t(kdm_hpa2)

for(i in 1:nrow(kdm.hpa.z)){
 kdm.hpa.z[i,] <- (kdm.hpa.z[i,]- mean(kdm.hpa.z[i,]))/(sd(kdm.hpa.z[i,]))
}
kdm.hpa.z[is.na(kdm.hpa.z)] <- 0

# Open a png file
png("kdm_hpa_z.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(kdm.hpa.z, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r specificity heatmap for hpa exp kat}
kat.hpa.z <- t(kat_hpa2)

for(i in 1:nrow(kat.hpa.z)){
 kat.hpa.z[i,] <- (kat.hpa.z[i,]- mean(kat.hpa.z[i,]))/(sd(kat.hpa.z[i,]))
}
kat.hpa.z[is.na(kat.hpa.z)] <- 0

# Open a png file
png("kat_hpa_z.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(kat.hpa.z, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r specificity heatmap for hpa exp hdac}
hdac.hpa.z <- t(hdac_hpa2)

for(i in 1:nrow(hdac.hpa.z)){
 hdac.hpa.z[i,] <- (hdac.hpa.z[i,]- mean(hdac.hpa.z[i,]))/(sd(hdac.hpa.z[i,]))
}
hdac.hpa.z[is.na(hdac.hpa.z)] <- 0

# Open a png file
png("hdac_hpa_z.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(hdac.hpa.z, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r hpa specificity}
png(filename= "HPA_exp_levels.png", res=300, width=2000, height=2500)
Heatmap(t(HPA_filter2), name="Level", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 5), width = unit(10, "cm"), height = unit(12, "cm"))
dev.off()

HPA_exp3 <- HPA_exp2[,-c(1,3,6)]
HPA_exp3$Level <- as.numeric(HPA_exp3$Level)

HPA_filter_cell <- HPA_exp3 %>% group_by(Cell.type, Gene.name) %>% mutate(Level= mean(Level)) %>% unique()
HPA_filter_cell <- HPA_filter_cell %>% pivot_wider(names_from= Cell.type, values_from= Level)
HPA_filter_cell <- data.frame(HPA_filter_cell)
rownames(HPA_filter_cell) <- HPA_filter_cell$Gene.name
HPA_filter_cell <- HPA_filter_cell[,-c(1)]
HPA_filter_cell[is.na(HPA_filter_cell)] <- 0
HPA_filter_cell <- filter(HPA_filter_cell, rownames(HPA_filter_cell) %in% kmt| rownames(HPA_filter_cell) %in% kdm| rownames(HPA_filter_cell) %in% kat| rownames(HPA_filter_cell) %in% hdac)

HPA_filter_cmx <- as.matrix(HPA_filter_cell)


png(filename= "HPA_exp_levels_cell.png", res=300, width=3000, height=3000)
Heatmap(HPA_filter_cmx, name="Level", column_names_gp = grid::gpar(fontsize = 5), row_names_gp = grid::gpar(fontsize = 5), width = unit(15, "cm"), height = unit(12, "cm"))
dev.off()
```

