---
title: "HPA + GTEX"
output: html_document
---
```{r document}
#This Rmd uses the second set of combined tissues which is more constrictive and excludes more tissues from analyses
#group GTEx logTPMs by expression level in HPA, ie high expression are gene-tissue pairs that have a protein level of 3 in HPA, filtered for modifiers
#histograms and boxplots of TPM distribution for each expression category, modifiers only
#t.tests to look for significant differences in mean TPM for each expression category, modifiers only
#bin GTEx TPMs by increments of 0.5 log(TPM+1) up to log(TPM+1)=2 is maximum bin category
#correlate Pearson R and Rsq between binned TPMs and protein levels
#Plot correlation values between RNA and protein by variance of the gene across all tissues

#marginal distribution plots for binned TPMS, all genes and modifiers only

```

```{r libraries}
library(matrixStats)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library("Hmisc")
library(ComplexHeatmap)
library("circlize")
library("RColorBrewer")
library(gdata)
library(igraph)

```


```{r read in data}
HPA_tissue_exp <- read.delim("~/Downloads/HPA_tissue_exp.tsv")
gtex <- read.csv("~/Downloads/gtex_medians_PC_only_wo_MT.csv", header=TRUE)


#read in modifier lists
kmt <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 2))
kdm <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 3))
kat <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 4))
hdac <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 5))


```
```{r clean gtex}
#remove first column of gtex
gtex <- gtex[,-c(1)]
#name+description table
gene_id_to_name <- gtex[,c(1,2)]
rownames(gtex) <- gtex$Name
gtex <- gtex[,-c(1) ]
gtex_mx <- apply(as.matrix(gtex, ncol= ncol(gtex)), 2, as.numeric)
gtex_mx[is.na(gtex_mx)] <- 0
rownames(gtex_mx)<- gtex$Description
gtex_mx <- gtex_mx[,-c(1)]


```
```{r modify HPA}
#convert detection levels to numbers
HPA_exp <- HPA_tissue_exp
for(i in 1:length(HPA_exp$Level)) {
        if (HPA_exp$Level[i] == "Not detected") {
HPA_exp$Level[i]=0
        } 
    else if (HPA_exp$Level[i]== "Low") {
HPA_exp$Level[i]=1
    } 
    else if (HPA_exp$Level[i]== "Medium") {
HPA_exp$Level[i]=2
    } 
    else {
HPA_exp$Level[i]=3
} 
}

HPA_exp$Level <- as.numeric(HPA_exp$Level)
HPA_exp2 <- HPA_exp
HPA_exp <- HPA_exp[,-c(1,4,6)]
hist(HPA_exp$Level)

```

```{r combine gtex tissues}
#Combine tissues in GTEX
Adipose <- c(rowMeans(gtex_mx[,1:2]))
Brain.Cerebellum <- c(rowMeans(gtex_mx[,11:12]))
Cervix <- c(rowMeans(gtex_mx[,24:25]))
Colon <- c(rowMeans(gtex_mx[,26:27]))
Esophagus <- c(rowMeans(gtex_mx[,28:30]))
Heart <- c(rowMeans(gtex_mx[,32:33]))
Kidney <- c(rowMeans(gtex_mx[,34:35]))
Skin <- c(rowMeans(gtex_mx[,45:46]))
gtex_mod <- cbind(gtex_mx[,-c(1, 2, 11, 12, 24:30, 32:35, 45, 46)], Adipose, Brain.Cerebellum, Cervix, Colon, Esophagus, Heart, Kidney, Skin)
#remove unmatched tissues from gtex mod
gtex_mod <- gtex_mod[,-c(2:4, 6, 7, 10, 12:16, 18, 25, 28)]
gtex_mod <- gtex_mod[,-c(7,23)]



```
```{r modify HPA}
#remove unwanted tissues
HPA_mod <- HPA_exp2[HPA_tissue_exp$Tissue != "appendix" & HPA_tissue_exp$Tissue != "nasopharynx" & HPA_tissue_exp$Tissue != "placenta" & HPA_tissue_exp$Tissue != "gallbladder" & HPA_tissue_exp$Tissue != "oral mucosa" & HPA_tissue_exp$Tissue != "parathyroid gland" & HPA_tissue_exp$Tissue != "rectum" & HPA_tissue_exp$Tissue != "smooth muscle" & HPA_tissue_exp$Tissue != "soft tissue 1" & HPA_tissue_exp$Tissue != "soft tissue 2" & HPA_tissue_exp$Tissue != "tonsil" & HPA_tissue_exp$Tissue != "N/A" & HPA_tissue_exp$Tissue != "hair" & HPA_tissue_exp$Tissue != "retina" & HPA_tissue_exp$Tissue != "thymus" & HPA_tissue_exp$Tissue != "cartilage" & HPA_tissue_exp$Tissue != "eye" & HPA_tissue_exp$Tissue != "dorsal raphe" & HPA_tissue_exp$Tissue != "choroid plexus" & HPA_tissue_exp$Tissue != "sole of foot" & HPA_tissue_exp$Tissue != "lactating breast" & HPA_tissue_exp$Tissue != "seminal vesicle" & HPA_tissue_exp$Tissue != "lymph node" & HPA_tissue_exp$Tissue != "epididymis" & HPA_tissue_exp$Tissue != "duodenum" & HPA_tissue_exp$Tissue != "bronchus" & HPA_tissue_exp$Tissue != "bone marrow",]
```
```{r filter for modifiers in HPA exp}

HPA_filter <- filter(HPA_mod, Gene.name %in% kmt| Gene.name %in% kdm| Gene.name %in% kat| Gene.name %in% hdac)

HPA_filter2 <- HPA_filter[,-c(1,4,6)]

HPA_filter2 <- HPA_filter2 %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique()

HPA_filter2 <- HPA_filter2 %>% pivot_wider(names_from= Tissue, values_from= Level)

HPA_filter2 <- data.frame(HPA_filter2)
rownames(HPA_filter2) <- HPA_filter2$Gene.name
HPA_filter2 <- HPA_filter2[,-c(1)]
HPA_filter2[is.na(HPA_filter2)] <- 0

```
```{r combine tissues in HPA}
Endometrium <- c(rowMeans(HPA_filter2[,c(9,10)]))
Skin <- c(rowMeans(HPA_filter2[,c(23,24)]))
Stomach <- c(rowMeans(HPA_filter2[,c(27,28)]))


HPA_filter2 <- cbind(HPA_filter2[,-c(9,10,23,24,27,28)], Endometrium, Skin, Stomach)


```
```{r change colnames}
#gtex_mod
colnames(gtex_mod) <- c("Adrenal.gland", "Bladder", "Brain.Caudate", "Brain.Cortex", "Brain.Hippocampus", "Breast", "Fallopian.tube", "Liver", "Lung", "Salivary.gland", "Skeletal.muscle", "Ovary", "Pancreas", "Prostate", "Small.intestine", "Spleen", "Stomach", "Testis", "Thyroid", "Uterus", "Vagina", "Adipose", "Brain.Cerebellum", "Cervix", "Colon", "Esophagus", "Heart", "Kidney", "Skin")

#HPA
colnames(HPA_filter2) <- c("Adipose", "Adrenal.gland", "Breast", "Brain.Caudate", "Brain.Cerebellum", "Brain.Cortex", "Cervix", "Colon", "Esophagus", "Fallopian.tube", "Heart", "Brain.Hippocampus", "Kidney", "Liver", "Lung", "Ovary", "Pancreas", "Prostate", "Salivary.gland", "Skeletal.muscle", "Small.intestine", "Spleen", "Testis", "Thyroid", "Bladder", "Vagina", "Uterus", "Skin", "Stomach")

#reorder columns
col_order <- c("Adipose", "Adrenal.gland", "Bladder", "Brain.Caudate", "Brain.Cerebellum", "Brain.Cortex", "Brain.Hippocampus", "Breast", "Cervix", "Colon", "Esophagus", "Fallopian.tube", "Heart", "Kidney", "Liver", "Lung", "Ovary", "Pancreas", "Prostate", "Salivary.gland", "Skeletal.muscle", "Skin", "Small.intestine", "Spleen", "Stomach", "Testis", "Thyroid", "Uterus", "Vagina")

gtex_mod <- gtex_mod[, col_order]
HPA_filter2 <- HPA_filter2[, col_order]

gtex_mod <- data.frame(gtex_mod)
gtex_filter <- filter(gtex_mod, rownames(gtex_mod) %in% kmt| rownames(gtex_mod) %in% kdm| rownames(gtex_mod) %in% kat| rownames(gtex_mod) %in% hdac)

is.element(rownames(gtex_filter), rownames(HPA_filter2))
gtex_filter2 <- gtex_filter[-c(1,13,18,20,27,29,30,40,41,44,46,56,58,60,61,63,65,67,69,71,75,82,83,85,86,93,95,101),]

is.element(rownames(gtex_filter2), rownames(HPA_filter2))
is.element(rownames(HPA_filter2), rownames(gtex_filter2))

row_order <- c(rownames(HPA_filter2))
gtex_filter2 <- gtex_filter2[row_order, ]





```
```{r indices}

HPA_filter_mx <- apply(as.matrix(HPA_filter2, ncol= ncol(HPA_filter2)), 2, as.numeric)
rownames(HPA_filter_mx) <- rownames(HPA_filter2)
high_exp <- which(HPA_filter_mx >= 2.5)
med_exp <- which(HPA_filter_mx < 2.5 & HPA_filter_mx >= 1.5)
low_exp <- which(HPA_filter_mx < 1.5 & HPA_filter_mx >= 0.5)
no_exp <- which(HPA_filter_mx < 0.5)

highest_exp <- which(HPA_filter_mx == 3)


gtex_filter_mx <- apply(as.matrix(gtex_filter2, ncol= ncol(gtex_filter2)), 2, as.numeric)
rownames(gtex_filter_mx) <- rownames(gtex_filter2)
gtex_filter_log <- log10(gtex_filter_mx +1)



gtex_high <- gtex_filter_log[high_exp]
gtex_med <- gtex_filter_log[med_exp]
gtex_low <- gtex_filter_log[low_exp]
gtex_none <- gtex_filter_log[no_exp]
gtex_highest <- gtex_filter_log[highest_exp]



```
```{r histogram}
hist(gtex_high)
hist(gtex_med)
hist(gtex_low)
hist(gtex_none)
hist(gtex_highest)

t.test(gtex_high, gtex_med, alternative=c("greater"))
#t = -1.5476, df = 883.66, p-value = 0.939
#alternative hypothesis: true difference in means is greater than 0
#95 percent confidence interval:
# -0.06873442         Inf
#mean of x   mean of y 
# 1.440575   1.473877 

t.test(gtex_med, gtex_low, alternative="greater")
#t = 2.3273, df = 970.95, p-value = 0.01008
#alternative hypothesis: true difference in means is greater than 0
#95 percent confidence interval:
# 0.01470789        Inf
#mean of x    mean of y 
# 1.473877     1.423603 
t.test(gtex_low, gtex_none, alternative="greater")
#t = 2.374, df = 1056.2, p-value = 0.008886
#alternative hypothesis: true difference in means is greater than 0
#95 percent confidence interval:
# 0.01580598        Inf
#mean of x mean of y 
# 1.423603  1.372041 
t.test(gtex_highest, gtex_med, alternative="greater")
#t = -0.81628, df = 609.75, p-value = 0.7927
#alternative hypothesis: true difference in means is greater than 0
#95 percent confidence interval:
# -0.05823161         Inf
#mean of x    mean of y 
# 1.454583     1.473877

length(gtex_high)
#424
length(gtex_med)
#759
length(gtex_low)
#477
length(gtex_none)
#156002


plot(HPA_filter_mx, gtex_filter_log)

```
```{r bin gtex TPMs}
gtex_bin <- gtex_filter_log

for(row in 1:nrow(gtex_bin)) {
  for(col in 1:ncol(gtex_bin)) {
        if (0 < gtex_bin[row,col] & gtex_bin[row,col] <= 0.5) {
gtex_bin[row,col]=1
        } 
    else if (0.5 < gtex_bin[row,col] & gtex_bin[row,col] <= 1) {
gtex_bin[row,col]=2
    } 
      else if (1 < gtex_bin[row,col] & gtex_bin[row,col] <= 1.5) {
gtex_bin[row,col]=2
      } 
      else if (1.5 < gtex_bin[row,col] & gtex_bin[row,col] <= 2) {
gtex_bin[row,col]=3
    } 
    else if (gtex_bin[row,col] > 2) {
gtex_bin[row,col]=4
    } 
    else {
gtex_bin[row,col]=0
} 
}}

```
```{r bin gtex TPMs, OG tissue set}

log_gtex <- log10(gtex_mx + 1)
gtex_bin_og <- log_gtex

for(row in 1:nrow(gtex_bin_og)) {
  for(col in 1:ncol(gtex_bin_og)) {
        if (0 < gtex_bin_og[row,col] & gtex_bin_og[row,col] <= 0.5) {
gtex_bin_og[row,col]=1
        } 
    else if (0.5 < gtex_bin_og[row,col] & gtex_bin_og[row,col] <= 1) {
gtex_bin_og[row,col]=2
    } 
      else if (1 < gtex_bin_og[row,col] & gtex_bin_og[row,col] <= 1.5) {
gtex_bin_og[row,col]=2
      } 
      else if (1.5 < gtex_bin_og[row,col] & gtex_bin_og[row,col] <= 2) {
gtex_bin_og[row,col]=3
    } 
    else if (gtex_bin_og[row,col] > 2) {
gtex_bin_og[row,col]=4
    } 
    else {
gtex_bin_og[row,col]=0
} 
  }}

gtex_bin_og <- t(gtex_bin_og)
res_gtex <- table(gtex_bin_og)

gtex_bin_df <- data.frame(t(gtex_bin_og))
gtex_bin_f <- filter(gtex_bin_df, rownames(gtex_bin_df) %in% kmt|rownames(gtex_bin_df) %in% kdm|rownames(gtex_bin_df) %in% kat|rownames(gtex_bin_df) %in% hdac)

res_gtex_f <- table(t(gtex_bin_f))

barplot(res_gtex, ylim=c(0,450000), ylab="Frequency", xlab="RNA Expression Level")
barplot(res_gtex_f, ylim=c(0,3500), ylab="Frequency", xlab="RNA Expression Level")






```
```{r correlate HPA and gtex binned}
rna.prot.cor <- cor(t(HPA_filter_mx), t(gtex_bin), method="pearson")
#SD is 0 for HDAC10 in gtex and for N6AMT1 in HPA.
rna.prot.cor[is.na(rna.prot.cor)] <- 0
rna.prot.sq <- rna.prot.cor^2

rna.prot.vec <- unmatrix(rna.prot.cor)
rna.prot.sq.vec <- unmatrix(rna.prot.sq)

hist(rna.prot.vec)
hist(rna.prot.sq)

Heatmap(rna.prot.cor, name= "R", row_names_side= "left", cluster_rows=FALSE, cluster_columns=FALSE, column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 7), col = colorRamp2(c(-0.25,-0.5,0,0.25,0.5,0.75,1), brewer.pal(n=7, name="RdBu")))
Heatmap(rna.prot.sq, name= "R-sq", row_names_side= "left", cluster_rows=FALSE, cluster_columns=FALSE, column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 7), col = colorRamp2(c(0,0.1,0.2,0.3,0.4,0.5,1), brewer.pal(n=7, name="Blues")))
```
```{r variance of modifiers in gtex}
gtex_var <- matrix(nrow=nrow(gtex_filter_mx), ncol=1)
rownames(gtex_var)<- rownames(gtex_filter_mx)
colnames(gtex_var)<- c("Variance Across Tissues")

for(row in 1:nrow(gtex_var)){
 gtex_var[row,] <- var(gtex_filter_mx[row,])
}

```
```{r correlation values}
correlation <- matrix(nrow=nrow(gtex_filter_mx), ncol=1)
rownames(correlation)<- rownames(gtex_filter_mx)
colnames(correlation) <- c("R")

for(row in 1:nrow(correlation)){
  correlation[row,] <- cor(HPA_filter_mx[row,], gtex_filter_mx[row,])
}



```
```{r combine and plot}
cor.by.var <- cbind(correlation, gtex_var)
cor.by.var <- data.frame(cor.by.var)
plot(gtex_var, correlation)
#same plot
plot(cor.by.var$Variance.Across.Tissues, cor.by.var$R)


rank(cor.by.var$Variance.Across.Tissues)
cor.by.var$Rank <- 75-rank(cor.by.var$Variance.Across.Tissues)
#rank 1 has highest variance; increase in rank means lower variance
plot(cor.by.var$Rank, cor.by.var$R)

```

