---
title: "HPA + GTEX"
output: html_document
---

```{r document}
#This Rmd uses the first tissue combination, which includes more tissues from both gtex and HPA
#non-MT GTEx dataset

#distribution of TPMs in entire nonMT GTEx dataset and for just modifiers, raw and log10. Density plot and histogram

#Cumulative frequency distribution of all TPMs in nonMT GTEx dataset and for just modifiers

#Pearson correlation R and R-sq between GTEx TPMs and HPA protein levels after combining tissues, all modifiers and pairwise

#TPM distribution for GTEx with modified tissue groups

#Pearson correlation for only data from HPA dataset after modifying tissue groups

#specificity heatmaps for HPA dataset after modifying tissue groups, by subcategory only, no code for entire list of modifiers

#code for binning GTEx TPMs by 0-33rd, 33rd-66th and 66th to 100th percentiles (not used)


```
```{r libraries}
library(matrixStats)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library("Hmisc")
library(ComplexHeatmap)
library("circlize")
library("RColorBrewer")
library(gdata)
```

```{r read in data}
HPA_tissue_exp <- read.delim("~/Downloads/HPA_tissue_exp.tsv")

gtex <- read.csv("~/Downloads/gtex_medians_PC_only_wo_MT.csv", header=TRUE)

#read in modifier lists
kmt <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 2))
kdm <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 3))
kat <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 4))
hdac <- t(read_excel("~/Desktop/GTEX/chromatin_modifiers_table.xlsx", 5))


```
```{r clean gtex}

#remove first column of gtex
gtex <- gtex[,-c(1)]
#name+description table
gene_id_to_name <- gtex[,c(1,2)]
View(gene_id_to_name)
rownames(gtex) <- gtex$Name
gtex <- gtex[,-c(1) ]
gtex_mx <- apply(as.matrix(gtex, ncol= ncol(gtex)), 2, as.numeric)
gtex_mx[is.na(gtex_mx)] <- 0
rownames(gtex_mx)<- gtex$Description
gtex_mx <- gtex_mx[,-c(1)]
```
```{r TPM distribution}
tpm.vec <- unmatrix(gtex_mx)
tpm.vec10 <- log10(unmatrix(gtex_mx)+1)
hist(tpm.vec, main= "GTEX TPM distribution", xlab= "Log(TPM+1)")
hist(tpm.vec10, main= "GTEX TPM distribution", xlab= "Log(TPM+1)")

png(filename="Gene_TPM_density_plot.png", res=300, width=2000, height=2000)
hist(tpm.vec10, freq=FALSE, main= "GTEX TPM distribution", xlab= "Log(TPM+1)", breaks=45, xlim=c(0,6), xaxp=c(0,6,20), yaxp=c(0,2,20))
dev.off()

hist(tpm.vec10) -> hvec10 # do a histogram of y and assign its info to h
hvec10$counts <- cumsum(hvec10$counts)/sum(hvec10$counts) # replace the cell freq.s by cumulative freq.s
png(filename="GTEX_TPM_cum_freq.png", res=300, width=2000, height=2000)
plot(hvec10, main= "GTEX TPM Cumulative frequency", xlab= "Log(TPM+1)", xlim=c(0,6), xaxp=c(0,6,30)) # plot a cumulative histogram of y
dev.off()



#right end of histogram
hist(tpm.vec10[tpm.vec10 > 3], main= "GTEX TPM distribution", xlab= "Log(TPM+1)")
hist(tpm.vec10[tpm.vec10 > 4], main= "GTEX TPM distribution", xlab= "Log(TPM+1)")

gtex_modifiers <- data.frame(gtex_mx)
gtex_modifiers <- filter(gtex_modifiers, rownames(gtex_modifiers) %in% kmt|rownames(gtex_modifiers) %in% kdm| rownames(gtex_modifiers) %in% kat| rownames(gtex_modifiers) %in% hdac)

gtex_modifiers_mx <- apply(as.matrix(gtex_modifiers, ncol= ncol(gtex_modifiers)), 2, as.numeric)
modifier.vec <- log10(unmatrix(gtex_modifiers_mx)+1)
modifier.vec.raw <- unmatrix(gtex_modifiers_mx)

hist(modifier.vec, main= "GTEX Chromatin Modifiers TPM distribution", xlab= "Log(TPM+1)")
hist(modifier.vec.raw[modifier.vec.raw <100], main= "GTEX Chromatin Modifiers TPM distribution", xlab= "TPM", breaks=20)

# cumulative freq distribution for modifiers only
hist(modifier.vec) -> hmod10 # do a histogram of y and assign its info to h
hmod10$counts <- cumsum(hmod10$counts)/sum(hmod10$counts) # replace the cell freq.s by cumulative freq.s
png(filename="GTEX_TPM_modifiers_cum_freq.png", res=300, width=2000, height=2000)
plot(hmod10, main= "Chromatin Modifiers TPM Cumulative frequency", xlab= "Log(TPM+1)", xlim=c(0,3), xaxp=c(0,3,30)) # plot a cumulative histogram of y
dev.off()

quantile(modifier.vec.raw, c(.33, .66, 1))
quantile(tpm.vec, c(.33, .66, 1))

quantile(modifier.vec, c(.33, .66, 1))
quantile(tpm.vec10, c(.33, .66, 1))



png(filename= "Gtex_log_TPM_noMT.png", res=300, width=2000, height=2000)
hist(tpm.vec10, main= "GTEX TPM distribution", xlab= "Log(TPM+1)")
dev.off()

png(filename= "Gtex_log_TPM_noMT_rt.png", res=300, width=2000, height=2000)
hist(tpm.vec10[tpm.vec10 > 3], main= "GTEX TPM distribution", xlab= "Log(TPM+1)")
dev.off()

png(filename= "Gtex_log_TPM_noMT_tail.png", res=300, width=2000, height=2000)
hist(tpm.vec10[tpm.vec10 > 4], main= "GTEX TPM distribution", xlab= "Log(TPM+1)")
dev.off()

png(filename= "Gtex_modifiers_noMT_TPM.png", res=300, width=2000, height=2000)
hist(modifier.vec, main= "GTEX Chromatin Modifiers TPM distribution", xlab= "Log(TPM+1)")
dev.off()

png(filename= "Gtex_modifiers_noMT_TPM_tail.png", res=300, width=2000, height=2000)
hist(modifier.vec[modifier.vec > 2.25], main= "GTEX Chromatin Modifiers TPM distribution", xlab= "Log(TPM+1)")
dev.off()



```
```{r  tissues in datsets}
hpa_tissues <- write.csv(unique(HPA_tissue_exp$Tissue), "HPA_tissues.csv")
gtex_tissues <- write.csv(colnames(gtex[2:55]), "gtex_tissues.csv")
```
```{r compare tissues}
#list of combined tissues
tissues <- read_excel("~/Desktop/chromatin_modifier_transcriptome_landscape/HPA_gtex_tissues.xlsx", 3)
#Combine tissues in GTEX
Adipose <- c(rowMeans(gtex_mx[,1:2]))
Brain.Cerebellum <- c(rowMeans(gtex_mx[,11:12]))
Cervix <- c(rowMeans(gtex_mx[,24:25]))
Colon <- c(rowMeans(gtex_mx[,26:27]))
Esophagus <- c(rowMeans(gtex_mx[,28:30]))
Heart <- c(rowMeans(gtex_mx[,32:33]))
Kidney <- c(rowMeans(gtex_mx[,34:35]))
Skin <- c(rowMeans(gtex_mx[,45:46]))
gtex_mod <- cbind(gtex_mx[,-c(1, 2, 11, 12, 24:30, 32:35, 45, 46)], Adipose, Brain.Cerebellum, Cervix, Colon, Esophagus, Heart, Kidney, Skin)
#remove unmatched tissues from gtex mod
gtex_mod <- gtex_mod[,-c(2:4, 6, 7, 10, 12:16, 18, 25, 28)]
```
```{r modify HPA}
#remove unwanted tissues
HPA_mod <- HPA_tissue_exp[HPA_tissue_exp$Tissue != "appendix" & HPA_tissue_exp$Tissue != "nasopharynx" & HPA_tissue_exp$Tissue != "placenta" & HPA_tissue_exp$Tissue != "gallbladder" & HPA_tissue_exp$Tissue != "oral mucosa" & HPA_tissue_exp$Tissue != "parathyroid gland" & HPA_tissue_exp$Tissue != "rectum" & HPA_tissue_exp$Tissue != "smooth muscle" & HPA_tissue_exp$Tissue != "soft tissue 1" & HPA_tissue_exp$Tissue != "soft tissue 2" & HPA_tissue_exp$Tissue != "tonsil" & HPA_tissue_exp$Tissue != "N/A" & HPA_tissue_exp$Tissue != "hair" & HPA_tissue_exp$Tissue != "retina" & HPA_tissue_exp$Tissue != "thymus" & HPA_tissue_exp$Tissue != "cartilage" & HPA_tissue_exp$Tissue != "eye" & HPA_tissue_exp$Tissue != "dorsal raphe" & HPA_tissue_exp$Tissue != "choroid plexus",]
```

```{r}
#convert detection levels to numbers
for(i in 1:length(HPA_mod$Level)) {
        if (HPA_mod$Level[i] == "Not detected") {
HPA_mod$Level[i]=0
        } 
    else if (HPA_mod$Level[i]== "Low") {
HPA_mod$Level[i]=1
    } 
    else if (HPA_mod$Level[i]== "Medium") {
HPA_mod$Level[i]=2
    } 
    else {
HPA_mod$Level[i]=3
} 
}

HPA_mod <- HPA_mod[,-c(1,4,6)]
HPA_mod$Level <- as.numeric(HPA_mod$Level)
```
```{r filter for modifiers}
#filter for all mod
all_HPA_mod <- filter(HPA_mod, Gene.name %in% kmt|Gene.name %in% kdm|Gene.name %in% kat|Gene.name %in% hdac)

all_HPA_mod <- all_HPA_mod %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique()
all_HPA_mod <- all_HPA_mod %>% pivot_wider(names_from= Tissue, values_from= Level)
all_HPA_mod <- data.frame(all_HPA_mod)
rownames(all_HPA_mod) <- all_HPA_mod$Gene.name
all_HPA_mod <- all_HPA_mod[,-c(1)]

#filter for kmt
kmt_HPA <- filter(HPA_mod, Gene.name %in% kmt)
kmt_HPA <- kmt_HPA %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique()
kmt_HPA <- kmt_HPA %>% pivot_wider(names_from= Tissue, values_from= Level)
kmt_HPA <- data.frame(kmt_HPA)
rownames(kmt_HPA) <- kmt_HPA$Gene.name
kmt_HPA <- kmt_HPA[,-c(1)]
#filter for kdm
kdm_HPA <- filter(HPA_mod, Gene.name %in% kdm)
kdm_HPA <- kdm_HPA %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique() %>% 
  pivot_wider(names_from= Tissue, values_from= Level) %>% 
  data.frame()
rownames(kdm_HPA) <- kdm_HPA$Gene.name
kdm_HPA <- kdm_HPA[,-c(1)]
#filter for kat
kat_HPA <- filter(HPA_mod, Gene.name %in% kat)
kat_HPA <- kat_HPA %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique() %>% 
  pivot_wider(names_from= Tissue, values_from= Level) %>% 
  data.frame()
rownames(kat_HPA) <- kat_HPA$Gene.name
kat_HPA <- kat_HPA[,-c(1)]
#filter for hdac
hdac_HPA <- filter(HPA_mod, Gene.name %in% hdac)
hdac_HPA <- hdac_HPA %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique() %>% 
  pivot_wider(names_from= Tissue, values_from= Level) %>% 
  data.frame()
rownames(hdac_HPA) <- hdac_HPA$Gene.name
hdac_HPA <- hdac_HPA[,-c(1)]

```
```{r alternate for loop}
#if looping through HPA_mod takes too long, filter first, then loop through each modifier list
HPA_mod <- HPA_tissue_exp[HPA_tissue_exp$Tissue != "appendix" & HPA_tissue_exp$Tissue != "nasopharynx" & HPA_tissue_exp$Tissue != "placenta" & HPA_tissue_exp$Tissue != "gallbladder" & HPA_tissue_exp$Tissue != "oral mucosa" & HPA_tissue_exp$Tissue != "parathyroid gland" & HPA_tissue_exp$Tissue != "rectum" & HPA_tissue_exp$Tissue != "smooth muscle" & HPA_tissue_exp$Tissue != "soft tissue 1" & HPA_tissue_exp$Tissue != "soft tissue 2" & HPA_tissue_exp$Tissue != "tonsil" & HPA_tissue_exp$Tissue != "N/A" & HPA_tissue_exp$Tissue != "hair" & HPA_tissue_exp$Tissue != "retina" & HPA_tissue_exp$Tissue != "thymus" & HPA_tissue_exp$Tissue != "cartilage" & HPA_tissue_exp$Tissue != "eye" & HPA_tissue_exp$Tissue != "dorsal raphe" & HPA_tissue_exp$Tissue != "choroid plexus",]
HPA_mod <- HPA_mod[,-c(1,4,6)]

#kmt
kmt_HPA <- filter(HPA_mod, Gene.name %in% kmt)

for(i in 1:length(kmt_HPA$Level)) {
        if (kmt_HPA$Level[i] == "Not detected") {
kmt_HPA$Level[i]=0
        } 
    else if (kmt_HPA$Level[i]== "Low") {
kmt_HPA$Level[i]=1
    } 
    else if (kmt_HPA$Level[i]== "Medium") {
kmt_HPA$Level[i]=2
    } 
    else {
kmt_HPA$Level[i]=3
} 
}
kmt_HPA$Level <- as.numeric(kmt_HPA$Level)
kmt_HPA <- kmt_HPA %>% group_by(Tissue, Gene.name) %>% mutate(Level= mean(Level)) %>% unique() %>% 
  pivot_wider(names_from= Tissue, values_from= Level) %>% 
  data.frame()
rownames(kmt_HPA) <- kmt_HPA$Gene.name
kmt_HPA <- kmt_HPA[,-c(1)]
```
```{r standardize names}
#Combine tissues in all_HPA_mod
Lung <- c(rowMeans(all_HPA_mod[,c(5,21)]))
Small.intestine <- c(rowMeans(all_HPA_mod[,c(11,31)]))
Uterus <- c(rowMeans(all_HPA_mod[,c(12:13)]))
Testis <- c(rowMeans(all_HPA_mod[,c(14,27,35)]))
Skin <- c(rowMeans(all_HPA_mod[,c(29,30)]))
Stomach <- c(rowMeans(all_HPA_mod[,c(33,34)]))

all_HPA_mod <- cbind(all_HPA_mod[,-c(5,21,11,31,12,13,14,27,35,29,30,33,34)], Lung, Small.intestine, Uterus, Testis, Stomach, Skin)

#Combine tissues in kmt_HPA
Lung <- c(rowMeans(kmt_HPA[,c(5,21)]))
Small.intestine <- c(rowMeans(kmt_HPA[,c(11,31)]))
Uterus <- c(rowMeans(kmt_HPA[,c(12:13)]))
Testis <- c(rowMeans(kmt_HPA[,c(14,27,35)]))
Skin <- c(rowMeans(kmt_HPA[,c(29,30)]))
Stomach <- c(rowMeans(kmt_HPA[,c(33,34)]))

kmt_HPA <- cbind(kmt_HPA[,-c(5,21,11,31,12,13,14,27,35,29,30,33,34)], Lung, Small.intestine, Uterus, Testis, Stomach, Skin)

#Combine tissues in kdm_HPA
Lung <- c(rowMeans(kdm_HPA[,c(5,21)]))
Small.intestine <- c(rowMeans(kdm_HPA[,c(11,31)]))
Uterus <- c(rowMeans(kdm_HPA[,c(12:13)]))
Testis <- c(rowMeans(kdm_HPA[,c(14,27,35)]))
Skin <- c(rowMeans(kdm_HPA[,c(29,30)]))
Stomach <- c(rowMeans(kdm_HPA[,c(33,34)]))

kdm_HPA <- cbind(kdm_HPA[,-c(5,21,11,31,12,13,14,27,35,29,30,33,34)], Lung, Small.intestine, Uterus, Testis, Stomach, Skin)

#Combine tissues in kat_HPA
Lung <- c(rowMeans(kat_HPA[,c(5,21)]))
Small.intestine <- c(rowMeans(kat_HPA[,c(11,31)]))
Uterus <- c(rowMeans(kat_HPA[,c(12:13)]))
Testis <- c(rowMeans(kat_HPA[,c(14,27,35)]))
Skin <- c(rowMeans(kat_HPA[,c(29,30)]))
Stomach <- c(rowMeans(kat_HPA[,c(33,34)]))

kat_HPA <- cbind(kat_HPA[,-c(5,21,11,31,12,13,14,27,35,29,30,33,34)], Lung, Small.intestine, Uterus, Testis, Stomach, Skin)

#Combine tissues in hdac_HPA
Lung <- c(rowMeans(hdac_HPA[,c(5,21)]))
Small.intestine <- c(rowMeans(hdac_HPA[,c(11,31)]))
Uterus <- c(rowMeans(hdac_HPA[,c(12:13)]))
Testis <- c(rowMeans(hdac_HPA[,c(14,27,35)]))
Skin <- c(rowMeans(hdac_HPA[,c(29,30)]))
Stomach <- c(rowMeans(hdac_HPA[,c(33,34)]))

hdac_HPA <- cbind(hdac_HPA[,-c(5,21,11,31,12,13,14,27,35,29,30,33,34)], Lung, Small.intestine, Uterus, Testis, Stomach, Skin)

```
```{r change colnames}
#gtex_mod
colnames(gtex_mod) <- c("Adrenal.gland", "Bladder", "Brain.Caudate", "Brain.Cortex", "Brain.Hippocampus", "Breast", "Lymphatic.tissue", "Fallopian.tube", "Liver", "Lung", "Salivary.gland", "Skeletal.muscle", "Ovary", "Pancreas", "Prostate", "Small.intestine", "Spleen", "Stomach", "Testis", "Thyroid", "Uterus", "Vagina", "Blood", "Adipose", "Brain.Cerebellum", "Cervix", "Colon", "Esophagus", "Heart", "Kidney", "Skin")

#HPA
colnames(all_HPA_mod) <- c("Adipose", "Adrenal.gland", "Blood", "Breast", "Brain.Caudate", "Brain.Cerebellum", "Brain.Cortex", "Cervix", "Colon", "Esophagus", "Fallopian.tube", "Heart", "Brain.Hippocampus", "Kidney", "Liver", "Lymphatic.tissue", "Ovary", "Pancreas", "Prostate", "Salivary.gland", "Skeletal.muscle", "Spleen", "Thyroid", "Bladder", "Vagina", "Lung", "Small.intestine", "Uterus", "Testis", "Stomach", "Skin")

chromatin_colnames <- c("Adipose", "Adrenal.gland", "Blood", "Breast", "Brain.Caudate", "Brain.Cerebellum", "Brain.Cortex", "Cervix", "Colon", "Esophagus", "Fallopian.tube", "Heart", "Brain.Hippocampus", "Kidney", "Liver", "Lymphatic.tissue", "Ovary", "Pancreas", "Prostate", "Salivary.gland", "Skeletal.muscle", "Spleen", "Thyroid", "Bladder", "Vagina", "Lung", "Small.intestine", "Uterus", "Testis", "Stomach", "Skin")
colnames(kmt_HPA) <- chromatin_colnames
colnames(kdm_HPA) <- chromatin_colnames
colnames(kat_HPA) <- chromatin_colnames
colnames(hdac_HPA) <- chromatin_colnames

#reorder columns
col_order <- c("Adipose", "Adrenal.gland", "Bladder", "Blood", "Brain.Caudate", "Brain.Cerebellum", "Brain.Cortex", "Brain.Hippocampus", "Breast", "Cervix", "Colon", "Esophagus", "Fallopian.tube", "Heart", "Kidney", "Liver", "Lung", "Lymphatic.tissue", "Ovary", "Pancreas", "Prostate", "Salivary.gland", "Skeletal.muscle", "Skin", "Small.intestine", "Spleen", "Stomach", "Testis", "Thyroid", "Uterus", "Vagina")

gtex_mod <- gtex_mod[, col_order]
all_HPA_mod <- all_HPA_mod[, col_order]


kmt_HPA <- kmt_HPA[, col_order]
kdm_HPA <- kdm_HPA[, col_order]
kat_HPA <- kat_HPA[, col_order]
hdac_HPA <- hdac_HPA[, col_order]

```
```{r filter GTEX}
gtex_mdf <- data.frame(gtex_mod)
all_gtex_mod <- filter(gtex_mdf, rownames(gtex_mdf) %in% kmt|rownames(gtex_mdf) %in% kdm|rownames(gtex_mdf) %in% kat|rownames(gtex_mdf) %in% hdac)

kmt_gtex <- filter(gtex_mdf, rownames(gtex_mdf) %in% kmt)
kdm_gtex <- filter(gtex_mdf, rownames(gtex_mdf) %in% kdm)
kat_gtex <- filter(gtex_mdf, rownames(gtex_mdf) %in% kat)
hdac_gtex <- filter(gtex_mdf, rownames(gtex_mdf) %in% hdac)

#convert to matrices
all_gtexm_mx <- t(apply(as.matrix(all_gtex_mod, ncol= ncol(all_gtex_mod)), 2, as.numeric))
colnames(all_gtexm_mx) <- rownames(all_gtex_mod)

kmt_gtex.mx <- t(apply(as.matrix(kmt_gtex, ncol= ncol(kmt_gtex)), 2, as.numeric))
colnames(kmt_gtex.mx) <- rownames(kmt_gtex)

kdm_gtex.mx <- t(apply(as.matrix(kdm_gtex, ncol= ncol(kdm_gtex)), 2, as.numeric))
colnames(kdm_gtex.mx) <- rownames(kdm_gtex)

kat_gtex.mx <- t(apply(as.matrix(kat_gtex, ncol= ncol(kat_gtex)), 2, as.numeric))
colnames(kat_gtex.mx) <- rownames(kat_gtex)

hdac_gtex.mx <- t(apply(as.matrix(hdac_gtex, ncol= ncol(hdac_gtex)), 2, as.numeric))
colnames(hdac_gtex.mx) <- rownames(hdac_gtex)
# pivot HPA

all_HPA_mod <- t(all_HPA_mod)
all_HPA_mod[is.na(all_HPA_mod)] <- 0


kmt_HPA <- t(kmt_HPA)
kdm_HPA <- t(kdm_HPA)
kat_HPA <- t(kat_HPA)
hdac_HPA <- t(hdac_HPA)
#convert NA to 0
kmt_HPA[is.na(kmt_HPA)] <- 0
kdm_HPA[is.na(kdm_HPA)] <- 0
kat_HPA[is.na(kat_HPA)] <- 0
hdac_HPA[is.na(hdac_HPA)] <- 0




```
```{r correlate all mod}
all.comp <- cor(all_HPA_mod, all_gtexm_mx, method= "pearson")
all.comp[is.na(all.comp)] <- 0
is.element(colnames(all.comp), rownames(all.comp))

all.comp <- all.comp[,-c(1,13,18,20,27,29,30,40,41,44,46,56,58,60,61,63,65,67,69,71,75,82,83,85,86,93,95,101)]

all.comp.order <- c(colnames(all.comp))
all.comp<- all.comp[all.comp.order, ]
all.comp.sq <- (all.comp)^2

png("HPA_gtex_all_mod_noMT.png", res=300, height=3000, width=3000 )
Heatmap(all.comp.sq, name= "R sq", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=FALSE, cluster_rows=FALSE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1), brewer.pal(n=7, name="Blues")))
dev.off

```
```{r tpm distribution gtex-mod}
mod.tpm.vec <- log(unmatrix(gtex_mod)+1)
hist(mod.tpm.vec, main= "GTEX TPM distribution", xlab= "Log(TPM+1)")
#right end of histogram
hist(mod.tpm.vec[mod.tpm.vec > 9], main= "GTEX TPM distribution", xlab= "Log(TPM+1)")
hist(mod.tpm.vec[mod.tpm.vec > 7], main= "GTEX TPM distribution", xlab= "Log(TPM+1)")

```
```{r correlate kmt}
kmt.comp <- cor(kmt_HPA, kmt_gtex.mx, method= "pearson")
kmt.comp[is.na(kmt.comp)] <- 0
is.element(colnames(kmt.comp), rownames(kmt.comp))
kmt.comp <- kmt.comp[,-c(1,8,13,15,16,20,24,28,35,36,38)]
kmt.row.order <- c(colnames(kmt.comp))
kmt.comp<- kmt.comp[kmt.row.order, ]
kmt.comp.sq <- (kmt.comp)^2

png("HPA_gtex_kmt_noMT.png", res=300, height=2000, width=2000 )
Heatmap(kmt.comp.sq, name= "R sq", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=FALSE, cluster_rows=FALSE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1), brewer.pal(n=7, name="Blues")))
dev.off

```
```{r correlate kdm}
kdm.comp <- cor(kdm_HPA, kdm_gtex.mx, method= "pearson")
kdm.comp[is.na(kdm.comp)] <- 0
is.element(colnames(kdm.comp), rownames(kdm.comp))
kdm.comp <- kdm.comp[,-c(5,10,11,16,17,18,19,20,21,24,26,29)]
kdm.row.order <- c(colnames(kdm.comp))
kdm.comp<- kdm.comp[kdm.row.order, ]
kdm.comp.sq <- (kdm.comp)^2

png("HPA_gtex_kdm_noMT.png", res=300, height=2000, width=2000 )
Heatmap(kdm.comp.sq, name= "R sq", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=FALSE, cluster_rows=FALSE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1), brewer.pal(n=7, name="Blues")))
dev.off()
```
```{r correlate kat}
kat.comp <- cor(kat_HPA, kat_gtex.mx, method= "pearson")
kat.comp[is.na(kat.comp)] <- 0
is.element(colnames(kat.comp), rownames(kat.comp))
kat.comp <- kat.comp[,-c(8,9,15,16,18)]
kat.row.order <- c(colnames(kat.comp))
kat.comp<- kat.comp[kat.row.order, ]
kat.comp.sq <- (kat.comp)^2

png("HPA_gtex_kat_noMT.png", res=300, height=2000, width=2000 )
Heatmap(kat.comp.sq, name= "R sq", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns= FALSE, cluster_rows= FALSE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1), brewer.pal(n=7, name="Blues")))
dev.off()
```
```{r correlate hdac}
hdac.comp <- cor(hdac_HPA, hdac_gtex.mx, method= "pearson")
hdac.comp[is.na(hdac.comp)] <- 0
is.element(colnames(hdac.comp), rownames(hdac.comp))
hdac.comp <- hdac.comp[,-c(3,9)]
hdac.row.order <- c(colnames(hdac.comp))
hdac.comp<- hdac.comp[hdac.row.order, ]
hdac.comp.sq <- (hdac.comp)^2

png("HPA_gtex_hdac_noMT.png", res=300, height=2000, width=2000 )
Heatmap(hdac.comp.sq, name= "R sq", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=FALSE, cluster_rows=FALSE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1), brewer.pal(n=7, name="Blues")))
dev.off()
```
```{r correlate kmt HPA only}
kmt.hpa.comp <- cor(kmt_HPA, method= "pearson")
kmt.hpa.comp[is.na(kmt.hpa.comp)] <- 0


Heatmap(kmt.hpa.comp, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=TRUE, cluster_rows=TRUE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.25, 0.5, 0.75, 1), brewer.pal(n=5, name="Blues")))

```
```{r correlate kdm HPA only}
kdm.hpa.comp <- cor(kdm_HPA, method= "pearson")
kdm.hpa.comp[is.na(kdm.hpa.comp)] <- 0


Heatmap(kdm.hpa.comp, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=TRUE, cluster_rows=TRUE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.25, 0.5, 0.75, 1), brewer.pal(n=5, name="Blues")))

```
```{r correlate kat HPA only}
kat.hpa.comp <- cor(kat_HPA, method= "pearson")
kat.hpa.comp[is.na(kat.hpa.comp)] <- 0


Heatmap(kat.hpa.comp, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=TRUE, cluster_rows=TRUE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.25, 0.5, 0.75, 1), brewer.pal(n=5, name="Blues")))

```
```{r correlate hdac HPA only}
hdac.hpa.comp <- cor(hdac_HPA, method= "pearson")
hdac.hpa.comp[is.na(hdac.hpa.comp)] <- 0


Heatmap(hdac.hpa.comp, name= "R", row_names_side= "left", show_column_dend= TRUE, show_row_dend= TRUE, cluster_columns=TRUE, cluster_rows=TRUE, column_names_gp = grid::gpar(fontsize = 8), row_names_gp = grid::gpar(fontsize = 8), col = colorRamp2(c(0, 0.25, 0.5, 0.75, 1), brewer.pal(n=5, name="Blues")))

```
```{r specificity heatmap for hpa mod kmt}
kmt.hpa.sd<- t(kmt_HPA)

for(i in 1:nrow(kmt.hpa.sd)){
 kmt.hpa.sd[i,] <- (kmt.hpa.sd[i,]- mean(kmt.hpa.sd[i,]))/(sd(kmt.hpa.sd[i,]))
}
kmt.hpa.sd[is.na(kmt.hpa.sd)] <- 0

# Open a png file
png("kmt_hpa_specificity.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(kmt.hpa.sd, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r specificity heatmap for hpaMod kdm}
kdm.hpa.sd<- t(kdm_HPA)

for(i in 1:nrow(kdm.hpa.sd)){
 kdm.hpa.sd[i,] <- (kdm.hpa.sd[i,]- mean(kdm.hpa.sd[i,]))/(sd(kdm.hpa.sd[i,]))
}

# Open a png file
png("kdm_hpa_specificity.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(kdm.hpa.sd, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r specificity heatmap for hpaMod kat}
kat.hpa.sd<- t(kat_HPA)

for(i in 1:nrow(kat.hpa.sd)){
 kat.hpa.sd[i,] <- (kat.hpa.sd[i,]- mean(kat.hpa.sd[i,]))/(sd(kat.hpa.sd[i,]))
}
kat.hpa.sd[is.na(kat.hpa.sd)] <- 0

# Open a png file
png("kat_hpa_specificity.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(kat.hpa.sd, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r specificity heatmap for hpaMod hdac}
hdac.hpa.sd<- t(hdac_HPA)

for(i in 1:nrow(hdac.hpa.sd)){
 hdac.hpa.sd[i,] <- (hdac.hpa.sd[i,]- mean(hdac.hpa.sd[i,]))/(sd(hdac.hpa.sd[i,]))
}

# Open a png file
png("hdac_hpa_specificity.png", res=300, width=2000, height=2000) 
# 2. Create a plot
Heatmap(hdac.hpa.sd, name="SD", column_names_gp = grid::gpar(fontsize = 7), row_names_gp = grid::gpar(fontsize = 6), width = unit(12, "cm"), height = unit(8, "cm"))
# Close the pdf file
dev.off() 

```
```{r bin GTEX mod}
gtex_bin <- gtex_mod
#bin using 33rd and 66th percentile of chromatin modifiers' TPM. 0= 0, 1= 0th to 33rd percentile, 2= 33rd to 66th percentile, 3= 66th to 100th percentile
for(row in 1:nrow(gtex_bin)) {
  for(col in 1:ncol(gtex_bin)) {
        if (0 < gtex_bin[row,col] & gtex_bin[row,col] <= 15.14129) {
gtex_bin[row,col]=1
        } 
    else if (15.14129 < gtex_bin[row,col] & gtex_bin[row,col] <= 34.20566) {
gtex_bin[row,col]=2
    } 
    else if (gtex_bin[row,col] > 34.20566) {
gtex_bin[row,col]=3
    } 
    else {
gtex_bin[row,col]=0
} 
}}


```

